let key='',token='',tenantId='';
window.addEventListener('DOMContentLoaded',async()=>{const ready=await window.tradeflowSubscriberAuthReady;const status=document.getElementById('assistant-status');const form=document.getElementById('assistant-form');const q=document.getElementById('assistant-question');const messages=document.getElementById('messages');const add=(text,kind='system',source='')=>{const el=document.createElement('div');el.className='assistant-message '+kind;el.textContent=text;if(source){const s=document.createElement('div');s.className='assistant-source';s.textContent=source;el.appendChild(s)}messages.appendChild(el);messages.scrollTop=messages.scrollHeight};key=ready?.key||'';token=ready?.session?.access_token||'';tenantId=ready?.tenantId||'';if(!key||!token||!tenantId){status.textContent='Subscriber authentication is not available.';return}const name=(ready.memberships||[]).find(x=>x.tenant_id===tenantId)?.tenant_name||'TradeFlow';document.getElementById('business-brand').textContent=name;status.textContent='Assistant gateway connected. No external AI provider is enabled yet.';form.addEventListener('submit',async e=>{e.preventDefault();const question=q.value.trim();if(!question)return;add(question,'user');q.value='';status.textContent='Retrieving approved TradeFlow knowledge…';try{const r=await fetch(window.TRADEFLOW_CONFIG.supabaseUrl+'/functions/v1/tradeflow-assistant',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({tenant_id:tenantId,question,mode:'help'})});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Assistant request failed.');const k=b.assistant?.knowledge||[];if(b.assistant?.provider==='none'){if(b.assistant?.fallback_answer)add(b.assistant.fallback_answer,'system',k.map(x=>x.title).join(' · '));else add('The TradeFlow gateway is working, but no matching approved guidance was found.','system');}status.textContent='Gateway response received. Provider: none.';}catch(err){add(err.message||String(err),'system');status.textContent='Assistant request failed.';}});});
const findResearch=document.getElementById('research-find');
const researchResults=document.getElementById('research-results');
const researchManufacturer=document.getElementById('research-manufacturer');
const researchModel=document.getElementById('research-model');
const researchPackage=document.getElementById('research-package');
const renderResearch=(payload)=>{
 researchResults.innerHTML='';
 const products=payload?.assistant?.products||[];
 if(!products.length){researchResults.innerHTML='<div class="assistant-note">No matching active Buying Catalogue product was found. No external research request was made.</div>';return;}
 products.forEach(item=>{
  const p=item.product,evidence=item.evidence||[];
  const box=document.createElement('div');box.className='research-product';
  const title=document.createElement('strong');title.textContent=[p.manufacturer,p.model,p.package_name].filter(Boolean).join(' — ');box.appendChild(title);
  const list=document.createElement('div');list.className='research-evidence';
  if(evidence.length){const h=document.createElement('div');h.textContent='Existing evidence:';list.appendChild(h);const ul=document.createElement('ul');evidence.forEach(e=>{const li=document.createElement('li');li.textContent=[e.evidence_type,e.source_name,e.observed_price===null?'':('£'+e.observed_price),e.checked_at?new Date(e.checked_at).toLocaleDateString('en-GB'):'' ].filter(Boolean).join(' · ');ul.appendChild(li)});list.appendChild(ul)}else{list.textContent='No existing research evidence is recorded for this product.'}
  box.appendChild(list);
  const approve=document.createElement('div');approve.className='research-approve';
  approve.innerHTML='<strong>Approve new evidence</strong><div class="research-approve-grid"><label>Evidence type<select class="ra-type"><option value="uk_new">UK New</option><option value="uk_used">UK Used</option><option value="overseas">Overseas</option></select></label><label>Source name<input class="ra-source" maxlength="300" placeholder="Retailer or marketplace"></label><label>Source URL<input class="ra-url" maxlength="2000" placeholder="https://..."></label><label>Observed price (GBP)<input class="ra-price" type="number" min="0" step="0.01"></label><label>Condition<select class="ra-condition"><option value="">Select condition</option><option value="sealed">Sealed</option><option value="opened_never_used">Opened / Never Used</option><option value="excellent">Excellent</option><option value="good">Good</option><option value="poor">Poor</option></select></label><label>Availability<input class="ra-availability" maxlength="100" placeholder="e.g. In stock"></label></div><label style="margin-top:10px">Notes<textarea class="ra-notes" maxlength="4000" placeholder="Evidence notes"></textarea></label><button type="button" class="ra-approve">Approve and save evidence</button><div class="ra-status assistant-status"></div>';
  box.appendChild(approve);researchResults.appendChild(box);
  approve.querySelector('.ra-approve').addEventListener('click',async()=>{
   const statusEl=approve.querySelector('.ra-status');statusEl.textContent='Saving approved evidence…';
   try{const body={tenant_id:tenantId,question:'Product research evidence approval',mode:'research',research_action:'approve',buying_product_id:p.id,evidence:{evidence_type:approve.querySelector('.ra-type').value,source_name:approve.querySelector('.ra-source').value.trim(),source_url:approve.querySelector('.ra-url').value.trim()||null,observed_price:approve.querySelector('.ra-price').value||null,item_condition:approve.querySelector('.ra-condition').value.trim()||null,availability:approve.querySelector('.ra-availability').value.trim()||null,notes:approve.querySelector('.ra-notes').value.trim()||null}};const rr=await fetch(window.TRADEFLOW_CONFIG.supabaseUrl+'/functions/v1/tradeflow-assistant',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});const rb=await rr.json().catch(()=>({}));if(!rr.ok)throw Error(rb.error||'Evidence approval failed.');statusEl.textContent='Approved evidence saved. The latest matching research can now be used by the existing buying calculation.';findResearch.click()}catch(err){statusEl.textContent=err.message||String(err)}});
 });
};
findResearch?.addEventListener('click',async()=>{const manufacturer=researchManufacturer.value.trim(),model=researchModel.value.trim();if(!manufacturer||!model){researchResults.innerHTML='<div class="assistant-note">Enter both manufacturer and model.</div>';return}researchResults.innerHTML='<div class="assistant-status">Finding the exact product and existing evidence…</div>';try{const rr=await fetch(window.TRADEFLOW_CONFIG.supabaseUrl+'/functions/v1/tradeflow-assistant',{method:'POST',headers:{apikey:key,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({tenant_id:tenantId,question:'Product research lookup',mode:'research',research_action:'lookup',manufacturer,model,package_name:researchPackage.value.trim()})});const rb=await rr.json().catch(()=>({}));if(!rr.ok)throw Error(rb.error||'Research lookup failed.');renderResearch(rb)}catch(err){researchResults.innerHTML='<div class="assistant-note">'+(err.message||String(err))+'</div>'}});
