const SUPABASE_URL='https://twfbmjwwqzxdxvclxbun.supabase.co';
const KEY_STORAGE='tradeflow_testlab_publishable_key';
const SESSION_STORAGE='tradeflow_testlab_session';
let key=null,session=null;
const $=id=>document.getElementById(id);
function status(text,type=''){const e=$('connection-status');e.textContent=text;e.className=`small ${type}`.trim()}
function msg(text,type=''){const e=$('create-message');e.textContent=text;e.className=type}
async function api(path,options={}){if(!key)throw new Error('TradeFlow Supabase is not connected.');const h=new Headers(options.headers||{});h.set('apikey',key);h.set('Content-Type','application/json');if(session?.access_token)h.set('Authorization',`Bearer ${session.access_token}`);const r=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:h});const t=await r.text();let b=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok){const d=b?.message||b?.msg||b?.error_description||b?.error||t||`HTTP ${r.status}`;const e=new Error(d);e.status=r.status;throw e}return b}
function saveSession(s){session=s||null;if(s?.access_token)localStorage.setItem(SESSION_STORAGE,JSON.stringify(s));else localStorage.removeItem(SESSION_STORAGE)}
async function signOut(){saveSession(null);location.reload()}
async function loadAdmin(){try{const rows=await api('/rest/v1/rpc/platform_admin_list_tenants',{method:'GET'});$('denied').hidden=true;$('admin').hidden=false;renderTenants(Array.isArray(rows)?rows:[])}catch(e){if(e.status===401||e.status===403||String(e.message).toLowerCase().includes('platform owner access required')){$('admin').hidden=true;$('denied').hidden=false}else{status(`Platform administration check failed: ${e.message}`,'error')}}}
function renderTenants(rows){if(!rows.length){$('tenant-list').innerHTML='<p class="small">No subscriber businesses exist yet.</p>';return}const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));$('tenant-list').innerHTML=`<table class="tenant-table"><thead><tr><th>Business</th><th>Slug</th><th>Status</th><th>Plan</th><th>Subscription</th><th>Members</th><th>Created</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${esc(r.tenant_name)}</strong></td><td>${esc(r.tenant_slug)}</td><td><span class="status ${esc(r.tenant_status)}">${esc(r.tenant_status)}</span></td><td>${esc(r.plan_name||r.plan_code||'—')}</td><td>${esc(r.subscription_status||'—')}</td><td>${esc(r.member_count)}</td><td>${esc(new Date(r.created_at).toLocaleDateString('en-GB'))}</td></tr>`).join('')}</tbody></table>`}
async function createTenant(e){e.preventDefault();const button=$('create');button.disabled=true;button.textContent='Creating…';msg('');try{const email=$('owner-email').value.trim();const users=await api('/rest/v1/rpc/platform_admin_find_user',{method:'POST',body:JSON.stringify({p_email:email})});const user=Array.isArray(users)?users[0]:null;if(!user)throw new Error('No TradeFlow Auth account was found for that owner email. Create the owner account first, then retry.');if(!user.email_confirmed)throw new Error('The owner Auth account exists but its email is not confirmed.');const id=await api('/rest/v1/rpc/platform_admin_create_tenant',{method:'POST',body:JSON.stringify({p_name:$('tenant-name').value.trim(),p_slug:$('tenant-slug').value.trim().toLowerCase(),p_owner_user_id:user.user_id,p_plan_code:$('plan-code').value})});msg(`Subscriber business created successfully. Tenant ID: ${id}`,'success');$('create-form').reset();await loadAdmin()}catch(e){msg(e.message||String(e),'error')}finally{button.disabled=false;button.textContent='Create subscriber business'}}
async function connect(k){try{if(!k||!k.startsWith('sb_')){status('Enter the TradeFlow Supabase publishable key beginning with sb_.','error');return}key=k;localStorage.setItem(KEY_STORAGE,k);await api('/auth/v1/settings');const saved=localStorage.getItem(SESSION_STORAGE);if(!saved){status('Connected. No signed-in TradeFlow account was found. Sign in through the Customer Test Lab first.','error');return}session=JSON.parse(saved);const user=await api('/auth/v1/user');session.user=user;localStorage.setItem(SESSION_STORAGE,JSON.stringify(session));$('config').hidden=true;$('app').hidden=false;$('session-email').textContent=user.email||'';await loadAdmin()}catch(e){key=null;status(`Connection failed: ${e.message||e}`,'error')}}
$('connect').addEventListener('click',()=>connect($('supabase-key').value.trim()));$('sign-out').addEventListener('click',signOut);$('refresh').addEventListener('click',loadAdmin);$('create-form').addEventListener('submit',createTenant);
const savedKey=localStorage.getItem(KEY_STORAGE);if(savedKey)$('supabase-key').value=savedKey;
