function renderPremiumHome(site,buyingCatalogue){
 const home=site.homepage||{},cats=buyingCatalogue?.categories||[],products=buyingCatalogue?.products||[],listings=window.__tradeflowListings||[];
 const t=site.template||'modern',name=site.name||'Your Business',headline=home.headline||'Buy, sell and trade with us',intro=home.intro||'A professional buying and selling service, built around your business.',buyHeading=home.buy_heading||'What we buy',buyIntro=home.buy_intro||'See the categories and products this business is currently looking for.',sellHeading=home.sell_heading||'What we sell',sellIntro=home.sell_intro||'Browse products currently available from this business.';
 const img=(url,alt,cls='')=>url?'<img class="'+cls+'" src="'+esc(url)+'" alt="'+esc(alt||name)+'" loading="lazy">':'<div class="tpl-demo-image '+cls+'"></div>';
 const logo=site.branding?.logo_url?'<img class="site-logo" src="'+esc(site.branding.logo_url)+'" alt="'+esc(name)+'">':'<span class="site-brand-text">'+esc(name)+'</span>';
 const headerLinks=Array.isArray(site.header?.links)?site.header.links:['home','buying','shop','about','contact']; const titleFor=slug=>slug==='home'?'Home':slug==='buying'?'What We Buy':slug==='shop'?'What We Sell':(Array.isArray(site.pages)?(site.pages.find(p=>p.slug===slug)?.title||slug):slug); const nav='<nav class="template-nav-public"><a class="template-brand-public" href="'+pageUrl('home')+'">'+logo+'</a><div class="template-links-public">'+headerLinks.filter(slug=>slug==='home'||(site.pages||[]).some(p=>p.slug===slug&&p.enabled!==false)).map(slug=>'<a href="'+pageUrl(slug)+'">'+esc(titleFor(slug))+'</a>').join('')+'<a class="account-link" href="'+customerUrl()+'">Customer Login</a></div></nav>';
 const tiles=Array.isArray(home.tiles)?home.tiles.slice(0,Number(home.tile_count)||8):[];
 const tileCards=tiles.map(tile=>'<article class="public-home-tile '+(tile.side==='buy'?'buy-tile':'sell-tile')+'"><div class="tile-image">'+(tile.image_url?'<img src="'+esc(tile.image_url)+'" alt="'+esc(tile.image_alt||tile.title||name)+'" loading="lazy">':'')+'</div><div class="tile-copy"><span>'+esc(tile.side==='buy'?'WHAT WE BUY':'WHAT WE SELL')+'</span><h3>'+esc(tile.title||'Featured')+'</h3><p>'+esc(tile.body||'')+'</p><a href="'+pageUrl(tile.side==='buy'?'buying':'shop')+'">'+esc(tile.cta||(tile.side==='buy'?'See what we buy':'View products'))+' →</a></div></article>').join('');
 const buyCards=cats.slice(0,8).map(cat=>{const items=products.filter(p=>p.category_id===cat.id);return '<article class="buy-category-card"><span>WHAT WE BUY</span><h3>'+esc(cat.name)+'</h3><p>'+esc(cat.description||'Selected products from our current buying list.')+'</p><div class="buy-product-list">'+items.slice(0,5).map(p=>'<b>'+esc(((p.manufacturer||'')+' '+(p.model||'')).trim()||'Product')+'</b>').join('')+'</div><small>'+items.length+' selected products</small><a class="category-sell-link" href="'+pageUrl('buying')+'&category='+encodeURIComponent(cat.id)+'">Sell your '+esc(cat.name)+' to us →</a></article>'}).join('');
 const buySection='<section class="template-section buying-block"><div class="section-intro"><span>01 / WHAT WE BUY</span><h2>'+esc(buyHeading)+'</h2><p>'+esc(buyIntro)+'</p><label class="buy-category-select"><span>What are you looking to sell?</span><select onchange="if(this.value)location.href=\''+pageUrl('buying')+'&category=\'+encodeURIComponent(this.value)"><option value="">Choose a category</option>'+cats.map(cat=>'<option value="'+esc(cat.id)+'">'+esc(cat.name)+'</option>').join('')+'</select></label></div><div class="buy-category-grid">'+(buyCards||'<div class="connected-empty">Our buying list is currently being updated.</div>')+'</div><a class="section-link" href="'+pageUrl('buying')+'">View everything we buy →</a></section>';
 const sellCards=listings.slice(0,6).map(p=>'<article class="sell-product-card"><div class="sell-photo">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="'+esc(p.title||'Product')+'">':'')+'</div><span>'+esc(p.category_name||'Product')+'</span><h3>'+esc(p.title||'Product')+'</h3><strong>'+esc(p.asking_price!=null?new Intl.NumberFormat('en-GB',{style:'currency',currency:p.currency||'GBP'}).format(Number(p.asking_price)):'View product')+'</strong></article>').join('');
 const sellSection='<section class="template-section selling-block"><div class="section-intro"><span>02 / WHAT WE SELL</span><h2>'+esc(sellHeading)+'</h2><p>'+esc(sellIntro)+'</p></div><div class="sell-product-grid">'+(sellCards||'<div class="connected-empty">Our retail products are currently being prepared.</div>')+'</div><a class="section-link" href="'+pageUrl('shop')+'">Open Retail Shop →</a></section>';
 const trust='<section class="trust-row"><div><b>What We Buy</b><span>Our current buying list is connected directly to TradeFlow.</span></div><div><b>Retail Shop</b><span>Published products are connected to our inventory.</span></div><div><b>Customer account</b><span>Quotes, orders and returns stay connected.</span></div></section>';
 const heroImg1=img(home.image_url,name+' hero image'),heroImg2=img(home.image_url2,name+' second image');
 let hero='';
 switch(t){
 case 'modern': hero='<section class="tpl-hero modern-hero"><div><span class="tpl-eyebrow">'+esc(name)+'</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">What We Sell</a></div></div><div class="hero-collage">'+heroImg1+heroImg2+'</div></section>';break;
 case 'heritage': hero='<section class="tpl-hero heritage-hero"><div class="heritage-copy"><span class="tpl-eyebrow">Established service</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">Sell to us</a><a href="'+pageUrl('shop')+'">Browse our shop</a></div></div><div class="heritage-image">'+heroImg1+'</div></section>';break;
 case 'tech': hero='<section class="tpl-hero tech-hero"><div><span class="tpl-code">TRADEFLOW / '+esc(name)+'</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tech-actions"><a href="'+pageUrl('buying')+'">01 / WHAT WE BUY</a><a href="'+pageUrl('shop')+'">02 / WHAT WE SELL</a></div></div>'+heroImg1+'</section>';break;
 case 'creative': hero='<section class="tpl-hero creative-hero"><div class="creative-image">'+heroImg1+'</div><div class="creative-copy"><span class="tpl-eyebrow">Your business</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><a class="creative-cta" href="'+pageUrl('buying')+'">Explore the business →</a></div></section>';break;
 case 'aerial': hero='<section class="tpl-hero aerial-hero"><div class="aerial-copy"><span class="tpl-code">BUYING / SELLING / TRADEFLOW</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">Retail Shop</a></div></div><div class="aerial-image">'+heroImg1+'</div></section>';break;
 case 'adventure': hero='<section class="tpl-hero adventure-hero">'+heroImg1+'<div class="adventure-copy"><span class="tpl-eyebrow">'+esc(name)+'</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">Explore the shop</a></div></div></section>';break;
 case 'professional': hero='<section class="tpl-hero professional-hero"><div><span class="tpl-eyebrow">Business information</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">Retail Shop</a></div></div><div class="professional-facts"><strong>BUYING</strong><span>'+cats.length+' categories</span><strong>SELLING</strong><span>'+listings.length+' published products</span></div></section>';break;
 case 'premium': hero='<section class="tpl-hero premium-hero-new"><div><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">Sell to us</a><a href="'+pageUrl('shop')+'">Shop products</a></div></div>'+heroImg1+'</section>';break;
 case 'marketplace': hero='<section class="tpl-hero marketplace-hero"><div><span class="tpl-code">BUY / SELL / TRADE</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="market-search">Search products or categories</div></div>'+heroImg1+'</section>';break;
 default: hero='<section class="tpl-hero statement-hero"><div class="statement-word">WE BUY.</div><div class="statement-copy"><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">See What We Buy</a><a href="'+pageUrl('shop')+'">See What We Sell</a></div></div>'+heroImg1+'</section>';
 }
 const tileSection=tileCards?'<section class="homepage-tiles-public"><div class="section-intro"><span>FEATURED</span><h2>More from us</h2></div><div class="homepage-tile-grid-public">'+tileCards+'</div></section>':'';
 return nav+hero+buySection+sellSection+tileSection+trust;
}

function renderPublicBuyingSection(catalogue){
 const products=Array.isArray(catalogue?.products)?catalogue.products:[];
 const categories=Array.isArray(catalogue?.categories)?catalogue.categories:[];
 if(!categories.length)return '<section class="public-tile-section public-buying-section"><div class="public-section-head"><div><span>What we buy</span><h2>What we are looking for</h2></div><p>This business is not currently showing a buying list online.</p></div></section>';
 const cards=categories.map(cat=>{const items=products.filter(p=>p.category_id===cat.id);return '<article class="public-buying-category"><div class="public-buying-category-head"><div><span>WHAT WE BUY</span><h3>'+esc(cat.name)+'</h3></div><strong>'+items.length+' '+(items.length===1?'product':'products')+'</strong></div>'+(cat.description?'<p class="public-buying-description">'+esc(cat.description)+'</p>':'')+'<ul>'+items.slice(0,8).map(p=>'<li><strong>'+esc(((p.manufacturer||'')+' '+(p.model||'')).trim()||'Product')+'</strong>'+(p.package_name?'<span>'+esc(p.package_name)+'</span>':'')+'</li>').join('')+'</ul>'+(items.length>8?'<p class="public-buying-more">+'+(items.length-8)+' more products</p>':'')+'<a class="public-buying-link" href="'+pageUrl('buying')+'">View full buying list</a></article>'}).join('');
 return '<section class="public-tile-section public-buying-section"><div class="public-section-head"><div><span>What we buy</span><h2>Sell your items to us</h2></div><p>These categories and products are selected from this business buying catalogue.</p></div><div class="public-buying-category-grid">'+cards+'</div></section>';
}
function renderPublicBuyingPage(catalogue){
 const products=Array.isArray(catalogue?.products)?catalogue.products:[];
 const categories=Array.isArray(catalogue?.categories)?catalogue.categories:[];
 if(!categories.length)return '<div class="public-buying-page-empty">This business is not currently showing a buying list online.</div>';
 const selectedId=new URLSearchParams(location.search).get('category');
 const shown=selectedId?categories.filter(c=>String(c.id)===String(selectedId)):categories;
 const selector='<div class="public-buying-filter"><label><span>Choose a category</span><select onchange="location.href=\''+pageUrl('buying')+'&category=\'+encodeURIComponent(this.value)"><option value="">All categories</option>'+categories.map(cat=>'<option value="'+esc(cat.id)+'" '+(String(cat.id)===String(selectedId)?'selected':'')+'>'+esc(cat.name)+'</option>').join('')+'</select></label></div>';
 const cards=shown.map(cat=>{const items=products.filter(p=>p.category_id===cat.id);const grouped=items.reduce((m,p)=>{const k=p.manufacturer||'Other';(m[k]??=[]).push(p);return m},{});const groups=Object.entries(grouped).map(([maker,list])=>'<div class="public-buying-manufacturer"><h3>'+esc(maker)+'</h3><div class="public-buying-product-list">'+list.map(p=>'<article><strong>'+esc(p.model||'Product')+'</strong>'+(p.package_name?'<span>'+esc(p.package_name)+'</span>':'')+(p.branch_name?'<small>'+esc(p.branch_name)+'</small>':'')+'</article>').join('')+'</div></div>').join('');return '<section class="public-buying-category-page"><div class="public-buying-category-head"><div><span>WHAT WE BUY</span><h2>'+esc(cat.name)+'</h2></div><strong>'+items.length+' '+(items.length===1?'product':'products')+'</strong></div>'+(cat.description?'<p>'+esc(cat.description)+'</p>':'')+groups+'<a class="category-sell-link" href="'+pageUrl('buying')+'&category='+encodeURIComponent(cat.id)+'">Continue with '+esc(cat.name)+' →</a></section>'}).join('');
 return selector+cards;
}

function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function customerUrl(){return tenantId?`customer-dashboard.html?tenant_id=${encodeURIComponent(tenantId)}`:'customer-dashboard.html'}
function pageUrl(slug){return `public-site.html?tenant_id=${encodeURIComponent(tenantId||'')}&page=${encodeURIComponent(slug)}${preview?'&preview=draft':''}`}
function applyContent(content){
 window.__tradeflowSiteContent=content;
 const site=content?.site||{},theme=site.theme||{},template=site.template||'business',typography=Object.assign({font:'Inter',hero:'large',section:'large',body:'standard',nav:'standard',button:'solid'},theme.typography||{}),sections=Object.assign({hero:true,dual:true,buy:true,sell:true,trust:true,shop:true},site.homepage?.sections||{});document.documentElement.style.setProperty('--accent',theme.accent||'#c46a2b');document.documentElement.style.setProperty('--font-family',typography.font||'Inter');document.documentElement.style.setProperty('--hero-size',typography.hero||'large');document.documentElement.style.setProperty('--section-size',typography.section||'large');document.documentElement.style.setProperty('--body-size',typography.body||'standard');document.documentElement.style.setProperty('--nav-size',typography.nav||'standard');document.documentElement.style.setProperty('--button-style',typography.button||'solid');document.body.dataset.font=typography.font||'Inter';document.body.dataset.heroSize=typography.hero||'large';document.body.dataset.sectionSize=typography.section||'large';document.body.dataset.bodySize=typography.body||'standard';document.body.dataset.navSize=typography.nav||'standard';document.body.dataset.buttonStyle=typography.button||'solid';document.body.dataset.headerStyle=typography.header||'standard';document.body.dataset.footerStyle=typography.footer||'simple';document.documentElement.style.setProperty('--page-bg',theme.page_bg||'#f5f6f8');document.documentElement.style.setProperty('--text-color',theme.text||'#17202a');document.documentElement.style.setProperty('--header-bg',theme.header_bg||'#ffffff');document.documentElement.style.setProperty('--buy-bg',theme.buy_bg||'#ffffff');document.documentElement.style.setProperty('--sell-bg',theme.sell_bg||'#f4f6f7');document.documentElement.style.setProperty('--footer-bg',theme.footer_bg||'#17202a');document.body.dataset.template=template;document.body.dataset.customTheme=theme.page_bg||theme.text||theme.header_bg||theme.buy_bg||theme.sell_bg||theme.footer_bg?'true':'false';
 const name=site.name||'TradeFlow';const headerLinks=Array.isArray(site.header?.links)?site.header.links:['home','buying','shop','about','contact'];const footerLinks=Array.isArray(site.footer?.links)?site.footer.links:['home','buying','shop','about','contact'];const titleFor=slug=>slug==='home'?'Home':slug==='buying'?'What We Buy':slug==='shop'?'What We Sell':(Array.isArray(site.pages)?(site.pages.find(p=>p.slug===slug)?.title||slug):slug);const legacyHeader=document.querySelector('.topbar');if(legacyHeader)legacyHeader.hidden=page==='home';$('site-name').textContent=name;$('footer-name').textContent=name;const brandText=$('site-brand-text');if(brandText)brandText.textContent=name;const logo=$('site-logo');if(logo){logo.src=site.branding?.logo_url||site.logo_url||'';logo.alt=name;logo.hidden=!logo.src;if(brandText)brandText.hidden=!!logo.src;}$('headline').textContent=site.homepage?.headline||'Buy, sell and trade with confidence.';document.title=name;
 renderBusinessExtras(site);
 renderPremiumHome(site,window.__tradeflowBuyingCatalogue||{categories:[],products:[]});const homeImage=$('home-image-wrap'),homeImg=$('home-image');$('home').hidden=true;$('home-features').hidden=true;$('premium-home').hidden=false;$('shop').hidden=page==='home'&&!sections.shop;if(homeImage&&homeImg){homeImg.src=site.homepage?.image_url||'';homeImg.alt=site.homepage?.image_alt||name;homeImage.hidden=!site.homepage?.image_url;}
 const pages=Array.isArray(site.pages)?site.pages:[];const nav=$('site-nav');nav.innerHTML='';
 const home=document.createElement('a');home.href=pageUrl('home');home.textContent='Home';nav.appendChild(home);
 headerLinks.filter(slug=>slug==='home'||pages.some(p=>p.slug===slug&&p.enabled!==false)).forEach(slug=>{const a=document.createElement('a');a.href=slug==='home'?pageUrl('home'):pageUrl(slug);a.textContent=titleFor(slug);nav.appendChild(a)});
 const login=document.createElement('a');login.className='login';login.href=customerUrl();login.textContent='Customer Login';nav.appendChild(login);const foot=document.querySelector('footer');if(foot){const links=footerLinks.filter(slug=>slug==='home'||pages.some(p=>p.slug===slug&&p.enabled!==false)).map(slug=>'<a href="'+pageUrl(slug)+'">'+esc(titleFor(slug))+'</a>').join('');foot.innerHTML='<span><strong>'+esc(name)+'</strong><br><small>'+esc(site.footer?.text||'Your business website powered by TradeFlow.')+'</small></span><span class="public-footer-links">'+links+'</span>';}
 $('hero-shop').href=pageUrl('shop');$('hero-sell').href=pageUrl('buying');$('sell-link').href=customerUrl();$('account-link').href=customerUrl();$('contact-link').href=pageUrl('contact');
 const selected=pages.find(p=>p.slug===page&&p.enabled!==false);if(page!=='home'&&selected){$('home').hidden=true;$('premium-home').hidden=true;$('home-features').hidden=true;$('shop').hidden=selected.slug!=='shop';$('contact').hidden=selected.slug==='shop';if(selected.slug==='shop'){$('shop-heading').textContent='What We Sell';$('shop-intro').textContent=selected.body||'Browse products currently published by this business.';}else if(selected.slug==='buying'){$('contact').hidden=true;$('page-heading').textContent=selected.title||'Sell to us';$('page-body').innerHTML=renderPublicBuyingPage(window.__tradeflowBuyingCatalogue||{categories:[],products:[]});}else{$('page-heading').textContent=selected.title||'Page';$('page-body').innerHTML=esc(selected.body||'').replace(/\n/g,'<br>');}
 const pageImage=$('page-image-wrap'),pageImg=$('page-image');if(pageImage&&pageImg){pageImage.innerHTML=(selected.image_url?'<img id="page-image" src="'+esc(selected.image_url)+'" alt="'+esc(selected.image_alt||selected.title||'Page image')+'">':'')+(selected.image_url2?'<img class="page-image-second" src="'+esc(selected.image_url2)+'" alt="'+esc(selected.image_alt2||selected.title||'Second page image')+'">':'');pageImage.hidden=!(selected.image_url||selected.image_url2);}}else{$('contact').hidden=true;$('premium-home').hidden=false}
}
function safeExternalUrl(value){try{const u=new URL(String(value||''),location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function renderBusinessExtras(site){
 const social=site.social||{},reviews=Array.isArray(site.reviews)?site.reviews:[],box=$('site-extras'),socialBox=$('social-links'),reviewBox=$('review-links'),shareBox=$('share-links');
 const socialItems=[['facebook','Facebook'],['instagram','Instagram'],['linkedin','LinkedIn'],['youtube','YouTube'],['tiktok','TikTok'],['x','X']].map(([key,label])=>{const url=safeExternalUrl(social[key]);return url?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+label+'</a>':''}).filter(Boolean);
 const reviewItems=reviews.map(r=>{const url=safeExternalUrl(r.url);return url&&r.label?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Read our '+esc(r.label)+' reviews</a>':''}).filter(Boolean);
 const pageShare=encodeURIComponent(location.href),shareTitle=encodeURIComponent(site.name||'Website');
 if(reviewBox)reviewBox.innerHTML=reviewItems.length?'<strong>Reviews</strong>'+reviewItems.join(''):''; 
 if(socialBox)socialBox.innerHTML=socialItems.length?'<strong>Follow us</strong>'+socialItems.join(''):'';
 if(shareBox)shareBox.innerHTML=social.show_share!==false?'<strong>Share</strong><button type="button" id="native-share">Share this website</button><a href="https://www.facebook.com/sharer/sharer.php?u='+pageShare+'" target="_blank" rel="noopener noreferrer">Facebook</a><a href="https://www.linkedin.com/sharing/share-offsite/?url='+pageShare+'" target="_blank" rel="noopener noreferrer">LinkedIn</a>':'';
 if(box)box.hidden=!(socialItems.length||reviewItems.length||(social.show_share!==false));
 const native=$('native-share');if(native)native.addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title:site.name||'Website',url:location.href})}catch(e){} }else{try{await navigator.clipboard.writeText(location.href);native.textContent='Link copied'}catch{native.textContent='Copy the website address to share'}}});
}
function money(value,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(Number(value))}catch{return`${currency} ${value}`}}
function renderListings(listings){const box=$('shop-list');if(!Array.isArray(listings)||!listings.length){box.innerHTML='<div class="empty-card">No products are currently available.</div>';return}box.innerHTML=listings.map(l=>`<article class="product-card"><div class="category">${esc(l.category_name||'Product')}</div><h3>${esc(l.title)}</h3><p>${esc(l.description||'Available from this business.')}</p><div class="product-price">${money(l.asking_price,l.currency)}</div><a class="buy" href="${customerUrl()}">View &amp; buy</a></article>`).join('')}
async function loadListings(tenant){if(!tenant)return;const listings=await api(`/rest/v1/rpc/get_published_store_listings?p_tenant_id=${encodeURIComponent(tenant)}`);window.__tradeflowListings=Array.isArray(listings)?listings:[];renderListings(listings);if(window.__tradeflowSiteContent)renderPremiumHome(window.__tradeflowSiteContent,window.__tradeflowBuyingCatalogue||{categories:[],products:[]})}
async function loadDraftPreview(){
 if(!tenantId)throw new Error('No subscriber tenant was supplied for preview.');
 let subscriberSession=null;try{subscriberSession=JSON.parse(localStorage.getItem('tradeflow_subscriber_session')||'null')}catch{}
 if(!subscriberSession?.access_token)throw new Error('Sign in to TradeFlow to preview the current draft website.');
 const headers={apikey:KEY,'Content-Type':'application/json',Authorization:'Bearer '+subscriberSession.access_token};
 const stateResponse=await fetch(SUPABASE_URL+'/rest/v1/tenant_site_state?select=draft_revision_id&tenant_id=eq.'+encodeURIComponent(tenantId),{headers});
 const stateText=await stateResponse.text();if(!stateResponse.ok)throw new Error(stateText||'Unable to load the website draft.');
 const states=stateText?JSON.parse(stateText):[];if(!Array.isArray(states)||states.length!==1)throw new Error('The subscriber website draft is not initialised.');
 const draftId=states[0].draft_revision_id;
 const draftResponse=await fetch(SUPABASE_URL+'/rest/v1/site_revisions?select=id,revision_number,status,content&tenant_id=eq.'+encodeURIComponent(tenantId)+'&id=eq.'+encodeURIComponent(draftId)+'&status=eq.draft',{headers});
 const draftText=await draftResponse.text();if(!draftResponse.ok)throw new Error(draftText||'Unable to load the website draft revision.');
 const drafts=draftText?JSON.parse(draftText):[];if(!Array.isArray(drafts)||drafts.length!==1)throw new Error('The current website draft revision could not be loaded.');
 window.__tradeflowBuyingCatalogue=await loadBuyingCatalogue(tenantId);applyContent(drafts[0].content);try{await Promise.race([loadListings(tenantId),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Retail products are taking too long to load.')),8000))])}catch(e){console.warn('TradeFlow shop listings did not load:',e);const shopList=$('shop-list');if(shopList)shopList.innerHTML='<div class="empty-card">Products are currently unavailable. The rest of the website is still available.</div>'}
}
async function loadBuyingCatalogue(tenant){
 if(!tenant)return {categories:[],products:[]};
 const rows=await api('/rest/v1/rpc/get_public_buying_catalogue?p_tenant_id='+encodeURIComponent(tenant));
 const products=Array.isArray(rows)?rows:[];
 const map=new Map();
 for(const p of products){if(!map.has(p.category_id))map.set(p.category_id,{id:p.category_id,name:p.category_name,slug:p.category_slug,description:p.category_description||'',product_count:0});map.get(p.category_id).product_count++;}
 return {categories:Array.from(map.values()),products};
}
async function loadByTenant(){if(!tenantId)throw new Error('No subscriber tenant was supplied. Open the public site with its tenant_id or active domain.');if(preview)return loadDraftPreview();const rows=await api('/rest/v1/rpc/get_published_sites');const selected=Array.isArray(rows)?rows.find(r=>r.tenant_id===tenantId):null;if(!selected)throw new Error('No published website was found for this subscriber.');try{window.__tradeflowBuyingCatalogue=await loadBuyingCatalogue(tenantId)}catch(e){console.warn('TradeFlow buying catalogue unavailable:',e);window.__tradeflowBuyingCatalogue={categories:[],products:[]}}applyContent(selected.content);await loadListings(tenantId)}
async function loadByHostname(){if(tenantId)return loadByTenant();if(!hostname||hostname==='localhost')return loadByTenant();const rows=await api(`/rest/v1/published_site_index?select=tenant_id,hostname,revision_number,content,published_at&hostname=eq.${encodeURIComponent(hostname)}&limit=1`);if(!Array.isArray(rows)||rows.length!==1)throw new Error('This domain is not connected to a published TradeFlow subscriber website.');const siteTenantId=rows[0].tenant_id;try{window.__tradeflowBuyingCatalogue=await loadBuyingCatalogue(siteTenantId)}catch(e){console.warn('TradeFlow buying catalogue unavailable:',e);window.__tradeflowBuyingCatalogue={categories:[],products:[]}}applyContent(rows[0].content);await loadListings(siteTenantId)}
(async()=>{try{$('site-name').textContent='Loading website…';$('headline').textContent='Please wait while the subscriber website loads.';const load=loadByHostname();await Promise.race([load,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Website loading timed out. Refresh the page and try again.')),20000))])}catch(error){$('site-name').textContent='Website unavailable';$('headline').textContent=error.message||String(error);$('status').textContent='Unable to load subscriber website';$('status').style.display='block'}})()
 const sellCards=listings.slice(0,6).map(p=>'<article class="sell-product-card"><div class="sell-photo">'+(p.image_url?'<img src="'+esc(p.image_url)+'" alt="'+esc(p.title||'Product')+'">':'')+'</div><span>'+esc(p.category_name||'Product')+'</span><h3>'+esc(p.title||'Product')+'</h3><strong>'+esc(p.asking_price!=null?new Intl.NumberFormat('en-GB',{style:'currency',currency:p.currency||'GBP'}).format(Number(p.asking_price)):'View product')+'</strong></article>').join('');
 const sellSection='<section class="template-section selling-block"><div class="section-intro"><span>02 / WHAT WE SELL</span><h2>'+esc(sellHeading)+'</h2><p>'+esc(sellIntro)+'</p></div><div class="sell-product-grid">'+(sellCards||'<div class="connected-empty">Our retail products are currently being prepared.</div>')+'</div><a class="section-link" href="'+pageUrl('shop')+'">Open Retail Shop →</a></section>';
 const trust='<section class="trust-row"><div><b>What We Buy</b><span>Our current buying list is connected directly to TradeFlow.</span></div><div><b>Retail Shop</b><span>Published products are connected to our inventory.</span></div><div><b>Customer account</b><span>Quotes, orders and returns stay connected.</span></div></section>';
 const heroImg1=img(home.image_url,name+' hero image'),heroImg2=img(home.image_url2,name+' second image');
 let hero='';
 switch(t){
 case 'modern': hero='<section class="tpl-hero modern-hero"><div><span class="tpl-eyebrow">'+esc(name)+'</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">What We Sell</a></div></div><div class="hero-collage">'+heroImg1+heroImg2+'</div></section>';break;
 case 'heritage': hero='<section class="tpl-hero heritage-hero"><div class="heritage-copy"><span class="tpl-eyebrow">Established service</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">Sell to us</a><a href="'+pageUrl('shop')+'">Browse our shop</a></div></div><div class="heritage-image">'+heroImg1+'</div></section>';break;
 case 'tech': hero='<section class="tpl-hero tech-hero"><div><span class="tpl-code">TRADEFLOW / '+esc(name)+'</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tech-actions"><a href="'+pageUrl('buying')+'">01 / WHAT WE BUY</a><a href="'+pageUrl('shop')+'">02 / WHAT WE SELL</a></div></div>'+heroImg1+'</section>';break;
 case 'creative': hero='<section class="tpl-hero creative-hero"><div class="creative-image">'+heroImg1+'</div><div class="creative-copy"><span class="tpl-eyebrow">Your business</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><a class="creative-cta" href="'+pageUrl('buying')+'">Explore the business →</a></div></section>';break;
 case 'aerial': hero='<section class="tpl-hero aerial-hero"><div class="aerial-copy"><span class="tpl-code">BUYING / SELLING / TRADEFLOW</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">Retail Shop</a></div></div><div class="aerial-image">'+heroImg1+'</div></section>';break;
 case 'adventure': hero='<section class="tpl-hero adventure-hero">'+heroImg1+'<div class="adventure-copy"><span class="tpl-eyebrow">'+esc(name)+'</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">Explore the shop</a></div></div></section>';break;
 case 'professional': hero='<section class="tpl-hero professional-hero"><div><span class="tpl-eyebrow">Business information</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">What We Buy</a><a href="'+pageUrl('shop')+'">Retail Shop</a></div></div><div class="professional-facts"><strong>BUYING</strong><span>'+cats.length+' categories</span><strong>SELLING</strong><span>'+listings.length+' published products</span></div></section>';break;
 case 'premium': hero='<section class="tpl-hero premium-hero-new"><div><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">Sell to us</a><a href="'+pageUrl('shop')+'">Shop products</a></div></div>'+heroImg1+'</section>';break;
 case 'marketplace': hero='<section class="tpl-hero marketplace-hero"><div><span class="tpl-code">BUY / SELL / TRADE</span><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="market-search">Search products or categories</div></div>'+heroImg1+'</section>';break;
 default: hero='<section class="tpl-hero statement-hero"><div class="statement-word">WE BUY.</div><div class="statement-copy"><h1>'+esc(headline)+'</h1><p>'+esc(intro)+'</p><div class="tpl-actions"><a href="'+pageUrl('buying')+'">See What We Buy</a><a href="'+pageUrl('shop')+'">See What We Sell</a></div></div>'+heroImg1+'</section>';
 }
 return nav+hero+buySection+sellSection+trust;
}

function renderPublicBuyingSection(catalogue){
 const products=Array.isArray(catalogue?.products)?catalogue.products:[];
 const categories=Array.isArray(catalogue?.categories)?catalogue.categories:[];
 if(!categories.length)return '<section class="public-tile-section public-buying-section"><div class="public-section-head"><div><span>What we buy</span><h2>What we are looking for</h2></div><p>This business is not currently showing a buying list online.</p></div></section>';
 const cards=categories.map(cat=>{const items=products.filter(p=>p.category_id===cat.id);return '<article class="public-buying-category"><div class="public-buying-category-head"><div><span>WHAT WE BUY</span><h3>'+esc(cat.name)+'</h3></div><strong>'+items.length+' '+(items.length===1?'product':'products')+'</strong></div>'+(cat.description?'<p class="public-buying-description">'+esc(cat.description)+'</p>':'')+'<ul>'+items.slice(0,8).map(p=>'<li><strong>'+esc(((p.manufacturer||'')+' '+(p.model||'')).trim()||'Product')+'</strong>'+(p.package_name?'<span>'+esc(p.package_name)+'</span>':'')+'</li>').join('')+'</ul>'+(items.length>8?'<p class="public-buying-more">+'+(items.length-8)+' more products</p>':'')+'<a class="public-buying-link" href="'+pageUrl('buying')+'">View full buying list</a></article>'}).join('');
 return '<section class="public-tile-section public-buying-section"><div class="public-section-head"><div><span>What we buy</span><h2>Sell your items to us</h2></div><p>These categories and products are selected from this business buying catalogue.</p></div><div class="public-buying-category-grid">'+cards+'</div></section>';
}
function renderPublicBuyingPage(catalogue){
 const products=Array.isArray(catalogue?.products)?catalogue.products:[];
 const categories=Array.isArray(catalogue?.categories)?catalogue.categories:[];
 if(!categories.length)return '<div class="public-buying-page-empty">This business is not currently showing a buying list online.</div>';
 return categories.map(cat=>{const items=products.filter(p=>p.category_id===cat.id);const grouped=items.reduce((m,p)=>{const k=p.manufacturer||'Other';(m[k]??=[]).push(p);return m},{});const groups=Object.entries(grouped).map(([maker,list])=>'<div class="public-buying-manufacturer"><h3>'+esc(maker)+'</h3><div class="public-buying-product-list">'+list.map(p=>'<article><strong>'+esc(p.model||'Product')+'</strong>'+(p.package_name?'<span>'+esc(p.package_name)+'</span>':'')+(p.branch_name?'<small>'+esc(p.branch_name)+'</small>':'')+'</article>').join('')+'</div></div>').join('');return '<section class="public-buying-page-category"><div class="public-section-head"><div><span>WHAT WE BUY</span><h2>'+esc(cat.name)+'</h2></div><p>'+esc(cat.description||'Products currently selected by this business.')+'</p></div>'+groups+'</section>'}).join('');
}
const SUPABASE_URL='https://twfbmjwwqzxdxvclxbun.supabase.co';const KEY='sb_publishable_AvcMgtUKV0O5k8H6k94mZQ_qH4pEIS9';const params=new URLSearchParams(location.search),tenantId=params.get('tenant_id'),page=params.get('page')||'home',preview=params.get('preview')==='draft',hostname=location.hostname,$=id=>document.getElementById(id);
async function api(path){if(!KEY)throw new Error('TradeFlow connection is not configured.');const response=await fetch(`${SUPABASE_URL}${path}`,{headers:{apikey:KEY,'Content-Type':'application/json'}});const text=await response.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!response.ok)throw new Error(body?.message||body?.msg||body?.error||text||`HTTP ${response.status}`);return body}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
function customerUrl(){return tenantId?`customer-dashboard.html?tenant_id=${encodeURIComponent(tenantId)}`:'customer-dashboard.html'}
function pageUrl(slug){return `public-site.html?tenant_id=${encodeURIComponent(tenantId||'')}&page=${encodeURIComponent(slug)}${preview?'&preview=draft':''}`}
function applyContent(content){
 window.__tradeflowSiteContent=content;
 const site=content?.site||{},theme=site.theme||{},template=site.template||'business',typography=Object.assign({font:'Inter',hero:'large',section:'large',body:'standard',nav:'standard',button:'solid'},theme.typography||{}),sections=Object.assign({hero:true,dual:true,buy:true,sell:true,trust:true,shop:true},site.homepage?.sections||{});document.documentElement.style.setProperty('--accent',theme.accent||'#c46a2b');document.documentElement.style.setProperty('--font-family',typography.font||'Inter');document.documentElement.style.setProperty('--hero-size',typography.hero||'large');document.documentElement.style.setProperty('--section-size',typography.section||'large');document.documentElement.style.setProperty('--body-size',typography.body||'standard');document.documentElement.style.setProperty('--nav-size',typography.nav||'standard');document.documentElement.style.setProperty('--button-style',typography.button||'solid');document.body.dataset.font=typography.font||'Inter';document.body.dataset.heroSize=typography.hero||'large';document.body.dataset.sectionSize=typography.section||'large';document.body.dataset.bodySize=typography.body||'standard';document.body.dataset.navSize=typography.nav||'standard';document.body.dataset.buttonStyle=typography.button||'solid';document.body.dataset.headerStyle=typography.header||'standard';document.body.dataset.footerStyle=typography.footer||'simple';document.documentElement.style.setProperty('--page-bg',theme.page_bg||'#f5f6f8');document.documentElement.style.setProperty('--text-color',theme.text||'#17202a');document.documentElement.style.setProperty('--header-bg',theme.header_bg||'#ffffff');document.documentElement.style.setProperty('--buy-bg',theme.buy_bg||'#ffffff');document.documentElement.style.setProperty('--sell-bg',theme.sell_bg||'#f4f6f7');document.documentElement.style.setProperty('--footer-bg',theme.footer_bg||'#17202a');document.body.dataset.template=template;document.body.dataset.customTheme=theme.page_bg||theme.text||theme.header_bg||theme.buy_bg||theme.sell_bg||theme.footer_bg?'true':'false';
 const name=site.name||'TradeFlow';const headerLinks=Array.isArray(site.header?.links)?site.header.links:['home','buying','shop','about','contact'];const footerLinks=Array.isArray(site.footer?.links)?site.footer.links:['home','buying','shop','about','contact'];const titleFor=slug=>slug==='home'?'Home':slug==='buying'?'What We Buy':slug==='shop'?'What We Sell':(Array.isArray(site.pages)?(site.pages.find(p=>p.slug===slug)?.title||slug):slug);const legacyHeader=document.querySelector('.topbar');if(legacyHeader)legacyHeader.hidden=page==='home';$('site-name').textContent=name;$('footer-name').textContent=name;const brandText=$('site-brand-text');if(brandText)brandText.textContent=name;const logo=$('site-logo');if(logo){logo.src=site.branding?.logo_url||site.logo_url||'';logo.alt=name;logo.hidden=!logo.src;if(brandText)brandText.hidden=!!logo.src;}$('headline').textContent=site.homepage?.headline||'Buy, sell and trade with confidence.';document.title=name;
 renderBusinessExtras(site);
 renderPremiumHome(site,window.__tradeflowBuyingCatalogue||{categories:[],products:[]});const homeImage=$('home-image-wrap'),homeImg=$('home-image');$('home').hidden=true;$('home-features').hidden=true;$('premium-home').hidden=false;$('shop').hidden=page==='home'&&!sections.shop;if(homeImage&&homeImg){homeImg.src=site.homepage?.image_url||'';homeImg.alt=site.homepage?.image_alt||name;homeImage.hidden=!site.homepage?.image_url;}
 const pages=Array.isArray(site.pages)?site.pages:[];const nav=$('site-nav');nav.innerHTML='';
 const home=document.createElement('a');home.href=pageUrl('home');home.textContent='Home';nav.appendChild(home);
 headerLinks.filter(slug=>slug==='home'||pages.some(p=>p.slug===slug&&p.enabled!==false)).forEach(slug=>{const a=document.createElement('a');a.href=slug==='home'?pageUrl('home'):pageUrl(slug);a.textContent=titleFor(slug);nav.appendChild(a)});
 const login=document.createElement('a');login.className='login';login.href=customerUrl();login.textContent='Customer Login';nav.appendChild(login);const foot=document.querySelector('footer');if(foot){const links=footerLinks.filter(slug=>slug==='home'||pages.some(p=>p.slug===slug&&p.enabled!==false)).map(slug=>'<a href="'+pageUrl(slug)+'">'+esc(titleFor(slug))+'</a>').join('');foot.innerHTML='<span><strong>'+esc(name)+'</strong><br><small>'+esc(site.footer?.text||'Your business website powered by TradeFlow.')+'</small></span><span class="public-footer-links">'+links+'</span>';}
 $('hero-shop').href=pageUrl('shop');$('hero-sell').href=pageUrl('buying');$('sell-link').href=customerUrl();$('account-link').href=customerUrl();$('contact-link').href=pageUrl('contact');
 const selected=pages.find(p=>p.slug===page&&p.enabled!==false);if(page!=='home'&&selected){$('home').hidden=true;$('premium-home').hidden=true;$('home-features').hidden=true;$('shop').hidden=selected.slug!=='shop';$('contact').hidden=selected.slug==='shop';if(selected.slug==='shop'){$('shop-heading').textContent='What We Sell';$('shop-intro').textContent=selected.body||'Browse products currently published by this business.';}else if(selected.slug==='buying'){$('contact').hidden=true;$('page-heading').textContent=selected.title||'Sell to us';$('page-body').innerHTML=renderPublicBuyingPage(window.__tradeflowBuyingCatalogue||{categories:[],products:[]});}else{$('page-heading').textContent=selected.title||'Page';$('page-body').innerHTML=esc(selected.body||'').replace(/\n/g,'<br>');}
 const pageImage=$('page-image-wrap'),pageImg=$('page-image');if(pageImage&&pageImg){pageImage.innerHTML=(selected.image_url?'<img id="page-image" src="'+esc(selected.image_url)+'" alt="'+esc(selected.image_alt||selected.title||'Page image')+'">':'')+(selected.image_url2?'<img class="page-image-second" src="'+esc(selected.image_url2)+'" alt="'+esc(selected.image_alt2||selected.title||'Second page image')+'">':'');pageImage.hidden=!(selected.image_url||selected.image_url2);}}else{$('contact').hidden=true;$('premium-home').hidden=false}
}
function safeExternalUrl(value){try{const u=new URL(String(value||''),location.href);return ['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function renderBusinessExtras(site){
 const social=site.social||{},reviews=Array.isArray(site.reviews)?site.reviews:[],box=$('site-extras'),socialBox=$('social-links'),reviewBox=$('review-links'),shareBox=$('share-links');
 const socialItems=[['facebook','Facebook'],['instagram','Instagram'],['linkedin','LinkedIn'],['youtube','YouTube'],['tiktok','TikTok'],['x','X']].map(([key,label])=>{const url=safeExternalUrl(social[key]);return url?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">'+label+'</a>':''}).filter(Boolean);
 const reviewItems=reviews.map(r=>{const url=safeExternalUrl(r.url);return url&&r.label?'<a href="'+esc(url)+'" target="_blank" rel="noopener noreferrer">Read our '+esc(r.label)+' reviews</a>':''}).filter(Boolean);
 const pageShare=encodeURIComponent(location.href),shareTitle=encodeURIComponent(site.name||'Website');
 if(reviewBox)reviewBox.innerHTML=reviewItems.length?'<strong>Reviews</strong>'+reviewItems.join(''):''; 
 if(socialBox)socialBox.innerHTML=socialItems.length?'<strong>Follow us</strong>'+socialItems.join(''):'';
 if(shareBox)shareBox.innerHTML=social.show_share!==false?'<strong>Share</strong><button type="button" id="native-share">Share this website</button><a href="https://www.facebook.com/sharer/sharer.php?u='+pageShare+'" target="_blank" rel="noopener noreferrer">Facebook</a><a href="https://www.linkedin.com/sharing/share-offsite/?url='+pageShare+'" target="_blank" rel="noopener noreferrer">LinkedIn</a>':'';
 if(box)box.hidden=!(socialItems.length||reviewItems.length||(social.show_share!==false));
 const native=$('native-share');if(native)native.addEventListener('click',async()=>{if(navigator.share){try{await navigator.share({title:site.name||'Website',url:location.href})}catch(e){} }else{try{await navigator.clipboard.writeText(location.href);native.textContent='Link copied'}catch{native.textContent='Copy the website address to share'}}});
}
function money(value,currency='GBP'){try{return new Intl.NumberFormat('en-GB',{style:'currency',currency}).format(Number(value))}catch{return`${currency} ${value}`}}
function renderListings(listings){const box=$('shop-list');if(!Array.isArray(listings)||!listings.length){box.innerHTML='<div class="empty-card">No products are currently available.</div>';return}box.innerHTML=listings.map(l=>`<article class="product-card"><div class="category">${esc(l.category_name||'Product')}</div><h3>${esc(l.title)}</h3><p>${esc(l.description||'Available from this business.')}</p><div class="product-price">${money(l.asking_price,l.currency)}</div><a class="buy" href="${customerUrl()}">View &amp; buy</a></article>`).join('')}
async function loadListings(tenant){if(!tenant)return;const listings=await api(`/rest/v1/rpc/get_published_store_listings?p_tenant_id=${encodeURIComponent(tenant)}`);window.__tradeflowListings=Array.isArray(listings)?listings:[];renderListings(listings);if(window.__tradeflowSiteContent)renderPremiumHome(window.__tradeflowSiteContent,window.__tradeflowBuyingCatalogue||{categories:[],products:[]})}
async function loadDraftPreview(){
 if(!tenantId)throw new Error('No subscriber tenant was supplied for preview.');
 let subscriberSession=null;try{subscriberSession=JSON.parse(localStorage.getItem('tradeflow_subscriber_session')||'null')}catch{}
 if(!subscriberSession?.access_token)throw new Error('Sign in to TradeFlow to preview the current draft website.');
 const headers={apikey:KEY,'Content-Type':'application/json',Authorization:'Bearer '+subscriberSession.access_token};
 const stateResponse=await fetch(SUPABASE_URL+'/rest/v1/tenant_site_state?select=draft_revision_id&tenant_id=eq.'+encodeURIComponent(tenantId),{headers});
 const stateText=await stateResponse.text();if(!stateResponse.ok)throw new Error(stateText||'Unable to load the website draft.');
 const states=stateText?JSON.parse(stateText):[];if(!Array.isArray(states)||states.length!==1)throw new Error('The subscriber website draft is not initialised.');
 const draftId=states[0].draft_revision_id;
 const draftResponse=await fetch(SUPABASE_URL+'/rest/v1/site_revisions?select=id,revision_number,status,content&tenant_id=eq.'+encodeURIComponent(tenantId)+'&id=eq.'+encodeURIComponent(draftId)+'&status=eq.draft',{headers});
 const draftText=await draftResponse.text();if(!draftResponse.ok)throw new Error(draftText||'Unable to load the website draft revision.');
 const drafts=draftText?JSON.parse(draftText):[];if(!Array.isArray(drafts)||drafts.length!==1)throw new Error('The current website draft revision could not be loaded.');
 window.__tradeflowBuyingCatalogue=await loadBuyingCatalogue(tenantId);applyContent(drafts[0].content);try{await Promise.race([loadListings(tenantId),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Retail products are taking too long to load.')),8000))])}catch(e){console.warn('TradeFlow shop listings did not load:',e);const shopList=$('shop-list');if(shopList)shopList.innerHTML='<div class="empty-card">Products are currently unavailable. The rest of the website is still available.</div>'}
}
async function loadBuyingCatalogue(tenant){
 if(!tenant)return {categories:[],products:[]};
 const rows=await api('/rest/v1/rpc/get_public_buying_catalogue?p_tenant_id='+encodeURIComponent(tenant));
 const products=Array.isArray(rows)?rows:[];
 const map=new Map();
 for(const p of products){if(!map.has(p.category_id))map.set(p.category_id,{id:p.category_id,name:p.category_name,slug:p.category_slug,description:p.category_description||'',product_count:0});map.get(p.category_id).product_count++;}
 return {categories:Array.from(map.values()),products};
}
async function loadByTenant(){if(!tenantId)throw new Error('No subscriber tenant was supplied. Open the public site with its tenant_id or active domain.');if(preview)return loadDraftPreview();const rows=await api('/rest/v1/rpc/get_published_sites');const selected=Array.isArray(rows)?rows.find(r=>r.tenant_id===tenantId):null;if(!selected)throw new Error('No published website was found for this subscriber.');try{window.__tradeflowBuyingCatalogue=await loadBuyingCatalogue(tenantId)}catch(e){console.warn('TradeFlow buying catalogue unavailable:',e);window.__tradeflowBuyingCatalogue={categories:[],products:[]}}applyContent(selected.content);await loadListings(tenantId)}
async function loadByHostname(){if(tenantId)return loadByTenant();if(!hostname||hostname==='localhost')return loadByTenant();const rows=await api(`/rest/v1/published_site_index?select=tenant_id,hostname,revision_number,content,published_at&hostname=eq.${encodeURIComponent(hostname)}&limit=1`);if(!Array.isArray(rows)||rows.length!==1)throw new Error('This domain is not connected to a published TradeFlow subscriber website.');const siteTenantId=rows[0].tenant_id;try{window.__tradeflowBuyingCatalogue=await loadBuyingCatalogue(siteTenantId)}catch(e){console.warn('TradeFlow buying catalogue unavailable:',e);window.__tradeflowBuyingCatalogue={categories:[],products:[]}}applyContent(rows[0].content);await loadListings(siteTenantId)}
(async()=>{try{$('site-name').textContent='Loading website…';$('headline').textContent='Please wait while the subscriber website loads.';const load=loadByHostname();await Promise.race([load,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Website loading timed out. Refresh the page and try again.')),20000))])}catch(error){$('site-name').textContent='Website unavailable';$('headline').textContent=error.message||String(error);$('status').textContent='Unable to load subscriber website';$('status').style.display='block'}})();