// TradeFlow subscriber authentication. Separate from Customer and Platform Owner sessions.
(()=>{const SUPABASE_URL='https://twfbmjwwqzxdxvclxbun.supabase.co',KEY='sb_publishable_AvcMgtUKV0O5k8H6k94mZQ_qH4pEIS9',SESSION_STORAGE='tradeflow_subscriber_session',TENANT_STORAGE='tradeflow_subscriber_tenant_id';const params=new URLSearchParams(location.search);let session=null,tenantId=params.get('tenant_id')||localStorage.getItem(TENANT_STORAGE)||null;try{session=JSON.parse(localStorage.getItem(SESSION_STORAGE)||'null')}catch{}let resolveReady;window.tradeflowSubscriberAuthReady=new Promise(r=>resolveReady=r);window.tradeflowSubscriberAuth={get key(){return KEY},get session(){return session},get tenantId(){return tenantId},tenants:{}};const style=document.createElement('style');style.textContent='.tradeflow-auth-overlay{position:fixed;inset:0;background:rgba(0,0,0,.48);display:flex;align-items:center;justify-content:center;z-index:9999;padding:24px}.tradeflow-auth-overlay[hidden]{display:none!important}.tradeflow-auth-card{width:min(440px,100%);background:#fff;border-radius:12px;padding:28px;box-shadow:0 18px 60px rgba(0,0,0,.25)}.tradeflow-auth-card h2{margin-top:0}.tradeflow-auth-card label{display:block;margin:14px 0 6px}.tradeflow-auth-card input{width:100%;box-sizing:border-box;padding:10px}.tradeflow-auth-card button{margin-top:16px;padding:10px 16px}.tradeflow-auth-error{color:#a00;margin-top:12px}.tradeflow-auth-small{font-size:13px;opacity:.75}';document.head.appendChild(style);
function save(){if(session?.access_token)localStorage.setItem(SESSION_STORAGE,JSON.stringify(session));else localStorage.removeItem(SESSION_STORAGE)}
function setTenant(id,label){if(!id)throw Error('No subscriber tenant selected.');tenantId=id;window.tradeflowSubscriberAuth.tenants[id]=label||id;localStorage.setItem(TENANT_STORAGE,id);const p=new URLSearchParams(location.search);p.set('tenant_id',id);history.replaceState(null,'',`${location.pathname}?${p.toString()}`);document.documentElement.dataset.tradeflowTenantId=id}
async function refreshSession(){if(!session?.refresh_token)throw Error('Subscriber session has expired. Please sign in again.');const r=await fetch(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:session.refresh_token})}),b=await r.json();if(!r.ok||!b?.access_token)throw Error(b?.error_description||b?.message||'Subscriber session refresh failed.');session={...b,user:session.user};save()}
async function request(path,o={},retry=true){const h=new Headers(o.headers||{});h.set('apikey',KEY);if(session?.access_token)h.set('Authorization',`Bearer ${session.access_token}`);if(o.body)h.set('Content-Type','application/json');const r=await fetch(`${SUPABASE_URL}${path}`,{...o,headers:h}),t=await r.text();let b=null;try{b=t?JSON.parse(t):null}catch{b=t}if(!r.ok){if(r.status===401&&retry&&session?.refresh_token){await refreshSession();return request(path,o,false)}throw Error(b?.message||b?.msg||b?.error_description||b?.error||t||`HTTP ${r.status}`)}return b}
async function memberships(){const rows=await request('/rest/v1/rpc/subscriber_get_my_memberships',{method:'POST',body:'{}'});return Array.isArray(rows)?rows:[]}
function overlay(message=''){let el=document.getElementById('tradeflow-subscriber-auth');if(!el){el=document.createElement('div');el.id='tradeflow-subscriber-auth';el.className='tradeflow-auth-overlay';el.innerHTML='<div class="tradeflow-auth-card"><h2>Subscriber sign in</h2><p class="tradeflow-auth-small">Sign in with your TradeFlow business account.</p><label>Email<input id="tradeflow-sub-email" type="email" autocomplete="username"></label><label>Password<input id="tradeflow-sub-password" type="password" autocomplete="current-password"></label><button id="tradeflow-sub-signin" type="button">Sign in</button><div id="tradeflow-sub-auth-error" class="tradeflow-auth-error"></div></div>';document.body.appendChild(el)}el.hidden=false;el.querySelector('#tradeflow-sub-auth-error').textContent=message;el.querySelector('#tradeflow-sub-signin').onclick=signIn;el.querySelector('#tradeflow-sub-password').onkeydown=e=>{if(e.key==='Enter')signIn()}}
function hide(){const el=document.getElementById('tradeflow-subscriber-auth');if(el)el.hidden=true}
async function establish(user){const rows=await memberships();if(!rows.length)throw Error('This account is not an active member of a TradeFlow business.');const selected=rows.find(r=>r.tenant_id===tenantId)||rows[0];setTenant(selected.tenant_id,selected.tenant_name||selected.business_name||selected.tenant_id);window.tradeflowSubscriberAuth.role=selected.role_code;window.tradeflowSubscriberAuth.user=user;window.tradeflowSubscriberAuth.tenantId=tenantId;window.tradeflowSubscriberAuth.memberships=rows;return rows}
async function verify(){if(!session?.access_token)return false;try{const user=await request('/auth/v1/user');session.user=user;save();await establish(user);return true}catch{return false}}
async function signIn(){const email=document.getElementById('tradeflow-sub-email').value.trim(),password=document.getElementById('tradeflow-sub-password').value,button=document.getElementById('tradeflow-sub-signin'),error=document.getElementById('tradeflow-sub-auth-error');if(!email||!password){error.textContent='Enter your email and password.';return}button.disabled=true;button.textContent='Signing in…';error.textContent='';try{session=await request('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});save();const user=await request('/auth/v1/user');session.user=user;save();await establish(user);hide();await renderTenantSwitcher();resolveReady(window.tradeflowSubscriberAuth)}catch(e){session=null;save();error.textContent=e.message||String(e)}finally{button.disabled=false;button.textContent='Sign in'}}
async function renderTenantSwitcher(){const host=document.getElementById('business-name');if(!host||!session?.access_token)return;try{const rows=await memberships();if(rows.length<2){host.textContent=rows[0]?.tenant_name||rows[0]?.business_name||window.tradeflowSubscriberAuth.tenants[tenantId]||'TradeFlow';return}const select=document.createElement('select');select.id='tradeflow-tenant-switcher';select.title='Switch business';select.style.cssText='padding:5px 8px;margin-right:8px';rows.forEach(r=>{const o=document.createElement('option');o.value=r.tenant_id;o.textContent=r.tenant_name||r.business_name||r.tenant_id;select.appendChild(o)});select.value=tenantId;select.onchange=()=>{setTenant(select.value,select.options[select.selectedIndex].textContent);location.reload()};host.replaceWith(select)}catch{}}
window.tradeflowSubscriberSignOut=()=>{session=null;save();localStorage.removeItem(TENANT_STORAGE);location.reload()};(async()=>{if(await verify()){hide();await renderTenantSwitcher();resolveReady(window.tradeflowSubscriberAuth)}else overlay()})();})();