const SUPABASE_URL='https://twfbmjwwqzxdxvclxbun.supabase.co';
const KEY_STORAGE='tradeflow_subscriber_publishable_key';
const SESSION_STORAGE='tradeflow_subscriber_session';
let supabaseKey=localStorage.getItem(KEY_STORAGE)||null,session=null;
const params=new URLSearchParams(location.search),tenantIdParam=params.get('tenant_id'),requestedTemplate=params.get('template');
let tenantId=tenantIdParam,draftRevisionId=null,currentTemplate=requestedTemplate||'business';
const $=id=>document.getElementById(id);
const name=$('builder-business-name'),headline=$('headline'),accent=$('accent'),brand=$('preview-brand'),title=$('preview-headline'),status=$('status'),site=$('site');
function setStatus(text,type=''){status.textContent=text||'';status.dataset.type=type}
function render(){brand.textContent=name.value||'Your Business';title.textContent=headline.value||'Buy, sell and trade with us';document.documentElement.style.setProperty('--accent',accent.value);site.className=`site template-${currentTemplate}`;const target=`customer-dashboard.html${tenantId?`?tenant_id=${encodeURIComponent(tenantId)}`:''}`;if($('preview-login'))$('preview-login').href=target;if($('preview-site'))$('preview-site').href=`public-site.html?tenant_id=${encodeURIComponent(tenantId||'')}`;}
const templateHeadlines={
 business:'A better way to buy and sell',
 marketplace:'Buy, sell and trade with confidence',
 services:'Professional service, made simple',
 editorial:'Good products. Properly presented.',
 minimal:'Quality products, simply presented.',
 retail:'Shop, sell and trade in one place.'
};
function applyTemplate(template){currentTemplate=templateHeadlines[template]?template:'business';headline.value=templateHeadlines[currentTemplate];render();document.querySelectorAll('[data-template]').forEach(b=>b.classList.toggle('selected',b.dataset.template===currentTemplate));setStatus(`${document.querySelector(`[data-template="${currentTemplate}"]`)?.querySelector('strong')?.textContent||'Template'} selected. Save the draft when ready.`);}
async function api(path,options={}){if(!supabaseKey)throw new Error('TradeFlow is not connected. Open the TradeFlow sign-in page first.');const headers=new Headers(options.headers||{});headers.set('apikey',supabaseKey);headers.set('Content-Type','application/json');if(session?.access_token)headers.set('Authorization',`Bearer ${session.access_token}`);const response=await fetch(`${SUPABASE_URL}${path}`,{...options,headers});const text=await response.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!response.ok){const detail=body?.msg||body?.message||body?.error_description||body?.error||text||`HTTP ${response.status}`;throw new Error(detail)}return body}
async function restoreSession(){if(!window.tradeflowSubscriberAuthReady)throw new Error('Subscriber authentication layer did not load.');const auth=await window.tradeflowSubscriberAuthReady;if(!auth?.session?.access_token)throw new Error('Subscriber authentication did not provide an access token.');supabaseKey=auth.key;session=auth.session;tenantId=auth.tenantId;return tenantId}
function buildContent(){return {schema_version:1,site:{name:name.value.trim()||'Your Business',pages:[],theme:{accent:accent.value},homepage:{headline:headline.value.trim()||'Buy, sell and trade with us'},navigation:[{label:'Home',path:'/'},{label:'Buy',path:'/buy'},{label:'Sell',path:'/sell'},{label:'Contact',path:'/contact'},{label:'Customer Login',path:'/customer'}],category_manifest:[],template:currentTemplate}}}
function loadContent(content){const s=content?.site||{};name.value=s.name||'Your Business';headline.value=s.homepage?.headline||'Buy, sell and trade with us';accent.value=s.theme?.accent||'#c46a2b';currentTemplate=s.template&&templateHeadlines[s.template]?s.template:'business';render();document.querySelectorAll('[data-template]').forEach(b=>b.classList.toggle('selected',b.dataset.template===currentTemplate));}
async function loadDraft(){const rows=await api(`/rest/v1/tenant_site_state?select=tenant_id,draft_revision_id,published_revision_id&tenant_id=eq.${encodeURIComponent(tenantId)}`);if(!Array.isArray(rows)||rows.length!==1)throw new Error('Subscriber website state is not initialised.');draftRevisionId=rows[0].draft_revision_id;const drafts=await api(`/rest/v1/site_revisions?select=id,revision_number,status,content&tenant_id=eq.${encodeURIComponent(tenantId)}&id=eq.${encodeURIComponent(draftRevisionId)}&status=eq.draft`);if(!Array.isArray(drafts)||drafts.length!==1)throw new Error('The current website draft revision could not be loaded.');loadContent(drafts[0].content);if(requestedTemplate)applyTemplate(requestedTemplate);setStatus(`Draft revision ${drafts[0].revision_number} loaded.`,'success')}
async function saveDraft(){if(!draftRevisionId)await loadDraft();setStatus('Saving website draft…');await api(`/rest/v1/site_revisions?id=eq.${encodeURIComponent(draftRevisionId)}&tenant_id=eq.${encodeURIComponent(tenantId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({content:buildContent()})});setStatus('Website draft saved to TradeFlow.','success')}
async function publish(){if(!draftRevisionId)await loadDraft();setStatus('Publishing website…');await api('/rest/v1/rpc/publish_site_revision',{method:'POST',body:JSON.stringify({p_tenant_id:tenantId,p_revision_id:draftRevisionId})});await loadDraft();setStatus('Website published. A new draft revision is now ready for further edits.','success')}
[name,headline,accent].forEach(el=>el.addEventListener('input',render));document.querySelectorAll('[data-template]').forEach(b=>b.addEventListener('click',()=>applyTemplate(b.dataset.template)));$('save-draft').addEventListener('click',()=>saveDraft().catch(e=>setStatus(e.message||String(e),'error')));$('publish').addEventListener('click',()=>publish().catch(e=>setStatus(e.message||String(e),'error')));$('preview-customer').addEventListener('click',()=>window.location.href=`customer-dashboard.html${tenantId?`?tenant_id=${encodeURIComponent(tenantId)}`:''}`);
(async()=>{try{await restoreSession();if(!tenantId)throw new Error('Subscriber authentication did not provide a tenant.');await loadDraft()}catch(error){setStatus(error.message||String(error),'error')}})();render();