import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const STRIPE_SECRET_KEY=Deno.env.get('STRIPE_SECRET_KEY');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers});
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers});
 if(req.method!=='POST')return json({error:'Method not allowed'},405);
 if(!STRIPE_SECRET_KEY)return json({error:'Stripe is not configured on the LIVE TradeFlow environment.'},503);
 const auth=req.headers.get('Authorization'); if(!auth)return json({error:'Authentication required'},401);
 try{
  const userRes=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:SERVICE_ROLE_KEY,Authorization:auth}});
  if(!userRes.ok)return json({error:'Authentication failed.'},401);
  const user=await userRes.json();
  const body=await req.json();
  const businessName=String(body?.business_name||'').trim();
  const planCode=String(body?.plan_code||'enhanced').trim();
  if(!businessName)return json({error:'Business name is required.'},400);
  if(planCode!=='enhanced')return json({error:'The TradeFlow subscription plan is required.'},400);
  const planRes=await fetch(SUPABASE_URL+'/rest/v1/plans?code=eq.enhanced&active=eq.true&select=id,code,name,description,monthly_price,currency,trial_days,stripe_monthly_price_id&limit=1',{headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}});
  if(!planRes.ok)return json({error:'Unable to load the TradeFlow plan.'},500);
  const plans=await planRes.json(); const plan=plans?.[0];
  if(!plan)return json({error:'TradeFlow plan is not configured.'},409);
  if(!plan.stripe_monthly_price_id)return json({error:'TradeFlow Stripe billing has not been connected yet. Please contact the platform owner.'},409);
  const origin=new URL(req.headers.get('origin')||req.headers.get('referer')||'').origin;
  if(!origin||origin==='null')return json({error:'Checkout origin could not be determined.'},400);
  const metadata={user_id:user.id,business_name:businessName,plan_code:plan.code};
  const params=new URLSearchParams();
  params.set('mode','subscription');
  params.set('line_items[0][price]',plan.stripe_monthly_price_id);
  params.set('line_items[0][quantity]','1');
  params.set('customer_email',String(user.email||''));
  params.set('client_reference_id',String(user.id));
  params.set('metadata[user_id]',String(user.id));
  params.set('metadata[business_name]',businessName);
  params.set('metadata[plan_code]',plan.code);
  params.set('subscription_data[trial_period_days]',String(Number(plan.trial_days??30)));
  params.set('subscription_data[metadata][user_id]',String(user.id));
  params.set('subscription_data[metadata][business_name]',businessName);
  params.set('subscription_data[metadata][plan_code]',plan.code);
  params.set('subscription_data[metadata][tradeflow_plan_id]',String(plan.id));
  params.set('success_url',`${origin}/subscriber-signup-success.html?session_id={CHECKOUT_SESSION_ID}`);
  params.set('cancel_url',`${origin}/subscriber-signup.html?plan=${encodeURIComponent(plan.code)}&checkout=cancelled`);
  const stripeRes=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded'},body:params});
  const stripe=await stripeRes.json();
  if(!stripeRes.ok)return json({error:stripe?.error?.message||'Unable to start Stripe subscription checkout.'},502);
  return json({checkout_url:stripe.url,session_id:stripe.id,trial_days:Number(plan.trial_days??30),monthly_price:Number(plan.monthly_price)});
 }catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}
});