import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const STRIPE_SECRET_KEY=Deno.env.get('STRIPE_SECRET_KEY');
const headers={'Content-Type':'application/json','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type'};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers});
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers});if(req.method!=='POST')return json({error:'Method not allowed'},405);if(!STRIPE_SECRET_KEY)return json({error:'Stripe is not configured on this TradeFlow environment yet.'},503);const auth=req.headers.get('Authorization');if(!auth)return json({error:'Authentication required'},401);try{const{tenant_id,order_id}=await req.json();if(!tenant_id||!order_id)return json({error:'tenant_id and order_id are required'},400);
const customerRes=await fetch(`${SUPABASE_URL}/rest/v1/rpc/customer_get_retail_order_for_checkout?p_tenant_id=${encodeURIComponent(tenant_id)}&p_order_id=${encodeURIComponent(order_id)}`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:auth}});if(!customerRes.ok)return json({error:'Unable to validate customer order access'},403);const orders=await customerRes.json();const order=Array.isArray(orders)?orders[0]:orders;if(!order)return json({error:'Order not found for this customer'},404);if(order.status!=='pending_payment')return json({error:'Order is not awaiting payment'},409);const amountDue=Number(order.amount_due);if(!Number.isFinite(amountDue)||amountDue<=0)return json({error:'Order has no amount due'},409);
// Generate a fresh idempotency key for each payment attempt. The database RPC still
// reuses an existing pending/processing attempt, while a failed attempt can be retried.
const attemptId=crypto.randomUUID();const idem=`tradeflow-order-${order_id}-attempt-${attemptId}`;
const paymentRes=await fetch(`${SUPABASE_URL}/rest/v1/rpc/customer_create_order_payment`,{method:'POST',headers:{apikey:SERVICE_ROLE_KEY,Authorization:auth,'Content-Type':'application/json'},body:JSON.stringify({p_tenant_id:tenant_id,p_order_id:order_id,p_idempotency_key:idem})});let paymentRows:any[]=[];if(paymentRes.ok){const body=await paymentRes.json();paymentRows=Array.isArray(body)?body:[body];}else{const existingRes=await fetch(`${SUPABASE_URL}/rest/v1/payment_records?tenant_id=eq.${encodeURIComponent(tenant_id)}&retail_order_id=eq.${encodeURIComponent(order_id)}&status=in.(pending,processing)&order=created_at.desc&limit=1`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}});if(existingRes.ok)paymentRows=await existingRes.json();if(!paymentRows.length)return json({error:`Unable to create payment record: ${await paymentRes.text()}`},400);}const payment=paymentRows[0];const paymentId=payment?.payment_id||payment?.id;if(!paymentId)return json({error:'Unable to create payment record'},500);
// If the active payment attempt is already linked to an open Stripe Checkout session,
// reuse that session rather than creating duplicate checkout sessions on repeated clicks.
const existingPaymentRes=await fetch(`${SUPABASE_URL}/rest/v1/payment_records?id=eq.${encodeURIComponent(paymentId)}&tenant_id=eq.${encodeURIComponent(tenant_id)}&select=provider,provider_payment_id,status&limit=1`,{headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`}});if(existingPaymentRes.ok){const existingRows=await existingPaymentRes.json();const existing=existingRows?.[0];if(existing?.provider==='stripe'&&existing?.provider_payment_id&&['pending','processing'].includes(existing.status)){const sessionRes=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(existing.provider_payment_id)}`,{headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`}});if(sessionRes.ok){const existingSession=await sessionRes.json();if(existingSession?.status==='open'&&existingSession?.url)return json({checkout_url:existingSession.url,session_id:existingSession.id,payment_id:paymentId,reused:true});}}}
const origin=req.headers.get('origin')||'https://laurendigitaluk.github.io';const baseUrl=origin.includes('://laurendigitaluk.github.io')?`${origin}/TradeFlow`:origin;const params=new URLSearchParams();params.set('mode','payment');
const methodsRes=await fetch(SUPABASE_URL+'/rest/v1/tenant_payment_methods?tenant_id=eq.'+encodeURIComponent(tenant_id)+'&method_code=in.(card,link,klarna,amazon_pay)&select=method_code,enabled&order=sort_order',{headers:{apikey:SERVICE_ROLE_KEY,Authorization:'Bearer '+SERVICE_ROLE_KEY}});
if(methodsRes.ok){
 const configured=await methodsRes.json();
 const enabled=new Set((Array.isArray(configured)?configured:[]).filter((x:any)=>x.enabled).map((x:any)=>x.method_code));
 const allowed=['card',...['link','klarna','amazon_pay'].filter(x=>enabled.has(x))];
 for(const code of [...new Set(allowed)]) params.append('allowed_payment_method_types[]',code);
}params.set('success_url',`${baseUrl}/customer-dashboard.html?tenant_id=${encodeURIComponent(tenant_id)}&payment=success&order_id=${encodeURIComponent(order_id)}`);params.set('cancel_url',`${baseUrl}/customer-basket.html?tenant_id=${encodeURIComponent(tenant_id)}&listing_id=${encodeURIComponent(order.listing_id||'')}&basket=1&payment=cancelled&order_id=${encodeURIComponent(order_id)}`);params.set('client_reference_id',order_id);params.set('customer_creation','if_required');params.set('line_items[0][quantity]','1');params.set('line_items[0][price_data][currency]',String(order.currency||'GBP').toLowerCase());params.set('line_items[0][price_data][unit_amount]',String(Math.round(amountDue*100)));params.set('line_items[0][price_data][product_data][name]',`TradeFlow order ${order.order_reference}`);params.set('metadata[tenant_id]',tenant_id);params.set('metadata[order_id]',order_id);params.set('metadata[payment_id]',paymentId);params.set('payment_intent_data[metadata][tenant_id]',tenant_id);params.set('payment_intent_data[metadata][order_id]',order_id);params.set('payment_intent_data[metadata][payment_id]',paymentId);
const stripeRes=await fetch('https://api.stripe.com/v1/checkout/sessions',{method:'POST',headers:{Authorization:`Bearer ${STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded','Idempotency-Key':idem},body:params});const stripe=await stripeRes.json();if(!stripeRes.ok)return json({error:stripe?.error?.message||'Stripe checkout session creation failed'},502);
const updateRes=await fetch(`${SUPABASE_URL}/rest/v1/payment_records?id=eq.${encodeURIComponent(paymentId)}&tenant_id=eq.${encodeURIComponent(tenant_id)}`,{method:'PATCH',headers:{apikey:SERVICE_ROLE_KEY,Authorization:`Bearer ${SERVICE_ROLE_KEY}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify({provider:'stripe',provider_payment_id:stripe.id,payment_method:'stripe_checkout',metadata:{source:'customer_portal',checkout_session_id:stripe.id,attempt_id:attemptId}})});if(!updateRes.ok)return json({error:'Payment session created but payment record could not be linked'},500);return json({checkout_url:stripe.url,session_id:stripe.id,payment_id:paymentId});}catch(e){return json({error:e instanceof Error?e.message:String(e)},500)}});