import "jsr:@supabase/supabase-js@2";
import {createClient} from "jsr:@supabase/supabase-js@2";
const U=Deno.env.get("SUPABASE_URL")!,K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,A=Deno.env.get("PORKBUN_API_KEY")!,S=Deno.env.get("PORKBUN_SECRET_API_KEY")!;
const H={"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"},J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H}),B="https://api.porkbun.com/api/json/v3";
Deno.serve(async req=>{
 if(req.method==="OPTIONS")return new Response("ok",{headers:H}); if(req.method!=="POST")return J({error:"Method not allowed"},405);
 const ah=req.headers.get("Authorization");if(!ah)return J({error:"Authentication required"},401);
 try{
  if(!A||!S)return J({error:"Porkbun production API credentials are not configured."},503);
  if(A.startsWith("pk1_sb_")||S.startsWith("sk1_sb_"))return J({error:"Porkbun sandbox credentials are configured for LIVE. Registration blocked."},503);
  const db=createClient(U,K),t=ah.replace(/^Bearer\s+/i,""),{data:{user}}=await db.auth.getUser(t);if(!user)return J({error:"Authentication required"},401);
  const b=await req.json().catch(()=>({})),tenantId=String(b?.tenant_id||"").trim(),orderId=String(b?.order_id||"").trim(),action=String(b?.action||"preflight");if(!tenantId||!orderId)return J({error:"tenant_id and order_id are required"},400);
  const {data:m}=await db.from("tenant_memberships").select("tenant_id").eq("tenant_id",tenantId).eq("user_id",user.id).eq("status","active").maybeSingle();if(!m)return J({error:"You do not have access to this TradeFlow workspace."},403);
  const {data:o,error:oe}=await db.from("tenant_domain_orders").select("id,tenant_id,hostname,tld,status,term_years,registrar_cost_usd,provider_order_id,expires_at,metadata").eq("id",orderId).eq("tenant_id",tenantId).maybeSingle();if(oe||!o)return J({error:"Domain order not found."},404);
  if(o.metadata?.sandbox===true||o.metadata?.porkbun_sandbox===true)return J({error:"Sandbox order blocked from LIVE registration."},409);
  if(o.status==="registered")return J({status:"REGISTERED",hostname:o.hostname,provider_order_id:o.provider_order_id||null,expires_at:o.expires_at});
  if(!["registrant_details_saved","registering","failed"].includes(o.status))return J({error:"Domain order is not ready for production registration.",status:o.status},409);
  const {data:r}=await db.from("tenant_domain_registrants").select("id,registrant_name,organisation,address_line1,address_line2,city,region,postal_code,country_code,email,phone").eq("domain_order_id",orderId).eq("tenant_id",tenantId).maybeSingle();if(!r)return J({error:"Saved registrant details not found."},409);
  const ph={"X-API-Key":A,"X-Secret-API-Key":S,"Content-Type":"application/json"},tld=String(o.tld||"").replace(/^\./,"").toLowerCase();
  const q=await fetch(B+"/domain/create/"+encodeURIComponent(o.hostname),{method:"POST",headers:ph,body:JSON.stringify({cost:0,agreeToTerms:"yes",dryRun:true})}),qd=await q.json().catch(()=>null);
  if(!q.ok||qd?.status!=="SUCCESS")return J({error:"Porkbun production preflight failed.",provider_code:qd?.code||null,provider_message:qd?.message||null,would_succeed:qd?.wouldSucceed??false},502);
  const current=Number(qd?.cost??qd?.price),saved=Number(o.registrar_cost_usd);if(!Number.isFinite(current)||!Number.isFinite(saved)||Math.round(current*100)!==Math.round(saved*100))return J({error:"Current Porkbun price differs from the price already paid. Registration blocked.",paid_registrar_cost_usd:saved,current_registrar_cost_usd:current},409);
  if(action==="preflight"){await db.from("tenant_domain_orders").update({failure_reason:null,metadata:{...(o.metadata||{}),porkbun_production_preflight_at:new Date().toISOString(),porkbun_production_preflight_would_succeed:qd?.wouldSucceed??true,porkbun_production_quoted_cost_usd:current,porkbun_production_sandbox:false}}).eq("id",orderId);return J({status:"PREFLIGHT_SUCCESS",hostname:o.hostname,registrar_cost_usd:current,would_succeed:qd?.wouldSucceed??true,request_id:qd?.requestId||null});}
  if(action!=="register")return J({error:"action must be preflight or register"},400);
  let providerOrderId=String(o.provider_order_id||"");
  if(!providerOrderId){
   const c=await fetch(B+"/domain/create/"+encodeURIComponent(o.hostname),{method:"POST",headers:{...ph,"Idempotency-Key":"tradeflow-register-"+o.id},body:JSON.stringify({cost:Math.round(current*100),agreeToTerms:"yes"})}),cd=await c.json().catch(()=>null);
   if(!c.ok||cd?.status!=="SUCCESS"){await db.from("tenant_domain_orders").update({status:"failed",failure_reason:String(cd?.code||cd?.message||"Porkbun registration failed.")}).eq("id",orderId);return J({error:"Porkbun production registration failed.",provider_code:cd?.code||null,provider_message:cd?.message||null},502);}
   providerOrderId=String(cd.orderId);await db.from("tenant_domain_orders").update({status:"registering",provider_order_id:providerOrderId,metadata:{...(o.metadata||{}),porkbun_registration_request_id:cd.requestId||null,porkbun_sandbox:false}}).eq("id",orderId);
  }
  const n=String(r.registrant_name).trim().split(/\s+/),contact={firstName:n[0]||"Registrant",lastName:n.slice(1).join(" ")||"Registrant",organization:r.organisation||"",address1:r.address_line1,address2:r.address_line2||"",city:r.city,state:r.region||"",postalCode:r.postal_code,country:r.country_code,phone:String(r.phone).replace(/^\+/,"").replace(/\D/g,""),phoneCountryCode:String(r.phone).match(/^\+(\d{1,3})/)?.[1]||(r.country_code==="GB"?"44":""),email:r.email};
  const cu=async(extra:any={})=>fetch(B+"/domain/updateContacts/"+encodeURIComponent(o.hostname),{method:"POST",headers:{...ph,"Idempotency-Key":"tradeflow-contact-"+o.id},body:JSON.stringify({contact,...extra})});
  let cr=await cu({dryRun:true}),cb=await cr.json().catch(()=>null);if(cb?.code==="ADDRESS_VALIDATION_REQUIRED"){cr=await cu({dryRun:true,addressValidationChoice:"use_as_entered"});cb=await cr.json().catch(()=>null);}
  if(!cr.ok||cb?.status!=="SUCCESS"){await db.from("tenant_domain_orders").update({status:"failed",failure_reason:"Domain registered, but registrant validation failed: "+String(cb?.code||cb?.message||"unknown"),metadata:{...(o.metadata||{}),porkbun_domain_created:true}}).eq("id",orderId);return J({error:"Domain registered, but Porkbun rejected the registrant details.",provider_order_id:providerOrderId,provider_code:cb?.code||null,provider_message:cb?.message||null,suggested_address:cb?.suggestedAddress||null},502);}
  let ca=await cu(),cab=await ca.json().catch(()=>null);if(cab?.code==="ADDRESS_VALIDATION_REQUIRED"){ca=await cu({addressValidationChoice:"use_as_entered"});cab=await ca.json().catch(()=>null);}
  if(!ca.ok||cab?.status!=="SUCCESS"){await db.from("tenant_domain_orders").update({status:"failed",failure_reason:"Domain registered, but registrant update failed: "+String(cab?.code||cab?.message||"unknown"),metadata:{...(o.metadata||{}),porkbun_domain_created:true}}).eq("id",orderId);return J({error:"Domain registered, but Porkbun could not apply the registrant details. It will not be registered again.",provider_order_id:providerOrderId,provider_code:cab?.code||null,provider_message:cab?.message||null,suggested_address:cab?.suggestedAddress||null},502);}
  const g=await fetch(B+"/domain/get/"+encodeURIComponent(o.hostname),{headers:{"X-API-Key":A,"X-Secret-API-Key":S}}),gd=await g.json().catch(()=>null);if(!g.ok||gd?.status!=="SUCCESS")return J({error:"Domain registered but final Porkbun verification failed. It will not be registered again.",provider_order_id:providerOrderId},502);
  const reg=gd.createDate?new Date(String(gd.createDate).replace(" ","T")+"Z").toISOString():new Date().toISOString(),exp=gd.expireDate?new Date(String(gd.expireDate).replace(" ","T")+"Z").toISOString():null,meta={sandbox:false,source:"tenant_domain_order",domain_order_id:o.id,provider_order_id:providerOrderId,registrant_record_id:r.id,contact_updated:true};
  const {data:td,error:te}=await db.from("tenant_domains").insert({tenant_id:tenantId,hostname:o.hostname,status:"active",domain_type:"custom",is_primary:false,acquisition_source:"purchased",registrar_provider:"porkbun",registered_at:reg,expires_at:exp,auto_renew:true,provider_metadata:meta}).select("id").single();if(te)return J({error:"Domain is registered, but TradeFlow could not create its tenant-domain record.",details:te.message,provider_order_id:providerOrderId},500);
  const {error:fe}=await db.from("tenant_domain_orders").update({status:"registered",provider_order_id:providerOrderId,purchased_at:reg,expires_at:exp,failure_reason:null,metadata:{...(o.metadata||{}),porkbun_registration_completed_at:new Date().toISOString(),porkbun_contact_update_succeeded:true,porkbun_sandbox:false,tenant_domain_id:td.id}}).eq("id",orderId);if(fe)return J({error:"Domain is registered, but TradeFlow could not finalise the order.",details:fe.message,provider_order_id:providerOrderId},500);
  return J({status:"REGISTERED",hostname:o.hostname,provider_order_id:providerOrderId,registered_at:reg,expires_at:exp,tenant_domain_id:td.id,sandbox:false});
 }catch(e){return J({error:e instanceof Error?e.message:String(e)},500);}
});