-- TradeFlow master catalogue snapshot metadata. System-owned catalogue only; no tenant/customer data.
insert into public.catalogue_master_categories(name,slug,active,sort_order) values
('Action Camera Accessories','action-camera-accessories',true,0),
('Action Cameras','action-cameras',true,0),
('Audio','audio',true,0),
('Audio & Video','audio-and-video',true,0),
('Camera & Video','camera-and-video',true,0),
('Camera Accessories','camera-accessories',true,0),
('Camera Equipment','camera-equipment',true,0),
('Camera Flash','camera-flash',true,0),
('Camera Rig','camera-rig',true,0),
('Camera Supports','camera-supports',true,0),
('Cameras','cameras',true,0),
('Continuous Lighting','continuous-lighting',true,0),
('Drone Accessories','drone-accessories',true,0),
('Drones','drones',true,0),
('Lens Accessories','lens-accessories',true,0),
('Lenses','lenses',true,0),
('Lighting','lighting',true,0),
('Lighting Modifier','lighting-modifier',true,0),
('Lighting Support','lighting-support',true,0),
('Optics','optics',true,0),
('Other Equipment','other-equipment',true,0),
('Phone Photography','phone-photography',true,0),
('Photography Lighting & Studio','photography-lighting-and-studio',true,0),
('Power & Batteries','power-and-batteries',true,0),
('Professional Audio','professional-audio',true,0),
('Studio Equipment','studio-equipment',true,0),
('Studio Lighting','studio-lighting',true,0),
('Supports & Stabilisation','supports-and-stabilisation',true,0),
('Tripods','tripods',true,0),
('Video Cameras','video-cameras',true,0),
('Video Equipment','video-equipment',true,0),
('Video Production Equipment','video-production-equipment',true,0) on conflict (slug) do update set name=excluded.name,active=excluded.active,sort_order=excluded.sort_order;

insert into public.catalogue_master_manufacturers(name,active) values
('Aaton',true),
('Accsoon',true),
('AJA',true),
('AKASO',true),
('Alphatron',true),
('amaran',true),
('Angelbird',true),
('Angenieux',true),
('Ansmann',true),
('Anton Bauer',true),
('Aputure',true),
('Arca Swiss',true),
('ARRI',true),
('Atomos',true),
('Audient',true),
('Audio-Technica',true),
('Autel Robotics',true),
('AVerMedia',true),
('B+W',true),
('Bebob',true),
('Benro',true),
('BetaFPV',true),
('Billingham',true),
('Blackmagic Design',true),
('Blueshape',true),
('Bowens',true),
('Bright Tangerine',true),
('Brinno',true),
('CaddxFPV',true),
('Canon',true),
('Casio',true),
('DJI',true),
('Edelkrone',true),
('Elinchrom',true),
('EMAX',true),
('FIMI',true),
('Freefly',true),
('Fujifilm',true),
('GEPRC',true),
('GoPro',true),
('Hasselblad',true),
('Hollyland',true),
('Holy Stone',true),
('HoverAir',true),
('Hubsan',true),
('iFlight',true),
('Insta360',true),
('Leica',true),
('Manfrotto',true),
('NEEWER',true),
('Nikon',true),
('Olympus/OM SYSTEM',true),
('Panasonic',true),
('Parrot',true),
('Pentax',true),
('Polaroid',true),
('Potensic',true),
('PowerVision',true),
('RadioMaster',true),
('RED Digital Cinema',true),
('RØDE',true),
('Sennheiser',true),
('Shure',true),
('Sigma',true),
('SJCAM',true),
('Skydio',true),
('SmallRig',true),
('Sony',true),
('Tamron',true),
('Tilta',true),
('Walkera',true),
('Yuneec',true),
('Z CAM',true) on conflict (name) do update set active=excluded.active;

with data(category_slug,name,slug,active,sort_order) as (values
('action-camera-accessories','Action Camera Accessories','action-camera-accessories',true,0),
('action-cameras','Action Cameras','action-cameras',true,0),
('audio','Audio Equipment','audio-equipment',true,0),
('audio','Professional Audio','professional-audio',true,0),
('audio','Wireless Audio Receivers','wireless-audio-receivers',true,0),
('audio','Wireless Microphone','wireless-microphone',true,0),
('audio','Wireless Sync Equipment','wireless-sync-equipment',true,0),
('audio-and-video','Microphone Stands','microphone-stands',true,0),
('audio-and-video','Microphones','microphones',true,0),
('camera-accessories','Bags & Cases','bags-and-cases',true,0),
('camera-accessories','Binocular Case','binocular-case',true,0),
('camera-accessories','Cables','cables',true,0),
('camera-accessories','Camera Accessories','camera-accessories',true,0),
('camera-accessories','Camera Extension','camera-extension',true,0),
('camera-accessories','Camera Media','camera-media',true,0),
('camera-accessories','Memory Card Readers','memory-card-readers',true,0),
('camera-accessories','Memory Cards','memory-cards',true,0),
('camera-accessories','Phone Grip','phone-grip',true,0),
('camera-accessories','USB-C Hub','usb-c-hub',true,0),
('camera-accessories','Viewfinders','viewfinders',true,0),
('camera-and-video','Action Camera Accessories','action-camera-accessories',true,0),
('camera-and-video','Camera Supports','camera-supports',true,0),
('camera-equipment','Camera Batteries','camera-batteries',true,0),
('camera-equipment','Camera Lenses','camera-lenses',true,0),
('camera-equipment','Camera Mounts','camera-mounts',true,0),
('camera-equipment','Cinema Rigs','cinema-rigs',true,0),
('camera-equipment','Drone Filters','drone-filters',true,0),
('camera-equipment','Filters','filters',true,0),
('camera-equipment','Flash Accessories','flash-accessories',true,0),
('camera-equipment','Gimbal Accessories','gimbal-accessories',true,0),
('camera-equipment','Phone Accessories','phone-accessories',true,0),
('camera-equipment','Phone Lenses','phone-lenses',true,0),
('camera-equipment','Phone Rigs','phone-rigs',true,0),
('camera-equipment','Tablet Holders','tablet-holders',true,0),
('camera-equipment','Tripod Heads','tripod-heads',true,0),
('camera-equipment','Tripods','tripods',true,0),
('camera-flash','Camera Flash','camera-flash',true,0),
('camera-flash','Flash Accessories','flash-accessories',true,0),
('camera-rig','Camera Cage','camera-cage',true,0),
('camera-rig','Camera Rig Accessory','camera-rig-accessory',true,0),
('camera-rig','Magic Arm','magic-arm',true,0),
('camera-rig','Phone Cage','phone-cage',true,0),
('camera-rig','Phone Rig Accessory','phone-rig-accessory',true,0),
('camera-rig','Phone Vlogging Kit','phone-vlogging-kit',true,0),
('camera-supports','Camera Mounts','camera-mounts',true,0),
('camera-supports','Camera Supports','camera-supports',true,0),
('camera-supports','Gimbal Head','gimbal-head',true,0),
('camera-supports','Overhead Tripod','overhead-tripod',true,0),
('camera-supports','Travel Tripod','travel-tripod',true,0),
('camera-supports','Tripod Dolly','tripod-dolly',true,0),
('camera-supports','Tripods','tripods',true,0),
('camera-supports','Video Tripods','video-tripods',true,0),
('cameras','Film Cameras','film-cameras',true,0),
('cameras','Photography Cameras','photography-cameras',true,0),
('continuous-lighting','Action Camera Cage','action-camera-cage',true,0),
('continuous-lighting','Continuous Lighting','continuous-lighting',true,0),
('continuous-lighting','Continuous Lighting Kit','continuous-lighting-kit',true,0),
('continuous-lighting','Light Modifiers','light-modifiers',true,0),
('continuous-lighting','Ring Lights','ring-lights',true,0),
('continuous-lighting','Spotlight Snoot','spotlight-snoot',true,0),
('continuous-lighting','Streaming Light','streaming-light',true,0),
('drone-accessories','Drone Accessories','drone-accessories',true,0),
('drone-accessories','Drone Controllers','drone-controllers',true,0),
('drone-accessories','Drone Goggles','drone-goggles',true,0),
('drone-accessories','Drone Payloads','drone-payloads',true,0),
('drone-accessories','Drone Remote Controllers','drone-remote-controllers',true,0),
('drone-accessories','FPV Equipment','fpv-equipment',true,0),
('drones','Camera Drones','camera-drones',true,0),
('drones','Underwater Drones','underwater-drones',true,0),
('drones','Water Drones','water-drones',true,0),
('lens-accessories','Phone Filter Kit','phone-filter-kit',true,0),
('lenses','Cinema Lenses','cinema-lenses',true,0),
('lenses','Lens Accessories','lens-accessories',true,0),
('lenses','Lens Control Systems','lens-control-systems',true,0),
('lenses','Phone Lens','phone-lens',true,0),
('lenses','Photography Lenses','photography-lenses',true,0),
('lighting','Camera Flashes & Strobes','camera-flashes-and-strobes',true,0),
('lighting','COB Video Light','cob-video-light',true,0),
('lighting','COB Video Light Kit','cob-video-light-kit',true,0),
('lighting','Continuous Lighting','continuous-lighting',true,0),
('lighting','Creator Video Light','creator-video-light',true,0),
('lighting','Flexible LED Light Kit','flexible-led-light-kit',true,0),
('lighting','Flexible RGB Video Light','flexible-rgb-video-light',true,0),
('lighting','LED Lighting Kit','led-lighting-kit',true,0),
('lighting','LED Panel','led-panel',true,0),
('lighting','LED Panel Kit','led-panel-kit',true,0),
('lighting','LED Panel Light Kit','led-panel-light-kit',true,0),
('lighting','LED Video Lights','led-video-lights',true,0),
('lighting','Light Modifiers','light-modifiers',true,0),
('lighting','Light Stands','light-stands',true,0),
('lighting','Lighting Accessory','lighting-accessory',true,0),
('lighting','Lighting Kit','lighting-kit',true,0),
('lighting','Outdoor Studio Flash','outdoor-studio-flash',true,0),
('lighting','RGB Softbox Lighting Kit','rgb-softbox-lighting-kit',true,0),
('lighting','RGB Tube Light','rgb-tube-light',true,0),
('lighting','RGB Tube Light Kit','rgb-tube-light-kit',true,0),
('lighting','RGB Video Light','rgb-video-light',true,0),
('lighting','Ring Light Kit','ring-light-kit',true,0),
('lighting','Ring Lights','ring-lights',true,0),
('lighting','Smart Lighting','smart-lighting',true,0),
('lighting','Softbox Lighting Kit','softbox-lighting-kit',true,0),
('lighting','Streaming Key Lights','streaming-key-lights',true,0),
('lighting','Studio Flash','studio-flash',true,0),
('lighting','Studio Lighting','studio-lighting',true,0),
('lighting','TTL Flash','ttl-flash',true,0),
('lighting-modifier','Parabolic Softbox','parabolic-softbox',true,0),
('lighting-modifier','Softbox','softbox',true,0),
('lighting-support','Boom Stand','boom-stand',true,0),
('lighting-support','C Stand','c-stand',true,0),
('lighting-support','Light Stand Pair','light-stand-pair',true,0),
('lighting-support','Light Stands','light-stands',true,0),
('lighting-support','Wall Boom Arm','wall-boom-arm',true,0),
('optics','Telescope Accessories','telescope-accessories',true,0),
('optics','Telescope Filters','telescope-filters',true,0),
('other-equipment','Cameras & Lenses','cameras-and-lenses',true,0),
('other-equipment','Night Vision','night-vision',true,0),
('other-equipment','Printer','printer',true,0),
('phone-photography','Phone Lens','phone-lens',true,0),
('photography-lighting-and-studio','COB & Continuous Video Lights','cob-and-continuous-video-lights',true,0),
('photography-lighting-and-studio','Flexible & Fabric LED Lights','flexible-and-fabric-led-lights',true,0),
('photography-lighting-and-studio','RGB Tube & Wand Lights','rgb-tube-and-wand-lights',true,0),
('photography-lighting-and-studio','Streaming Key Lights','streaming-key-lights',true,0),
('power-and-batteries','Batteries','batteries',true,0),
('power-and-batteries','Battery Grip','battery-grip',true,0),
('power-and-batteries','Camera Batteries','camera-batteries',true,0),
('power-and-batteries','Power Equipment','power-equipment',true,0),
('professional-audio','Audio Accessory','audio-accessory',true,0),
('studio-equipment','Backdrops','backdrops',true,0),
('studio-equipment','Background Support','background-support',true,0),
('studio-equipment','Bags & Cases','bags-and-cases',true,0),
('studio-equipment','Boom Arms','boom-arms',true,0),
('studio-equipment','Flash Accessories','flash-accessories',true,0),
('studio-equipment','Light Stands','light-stands',true,0),
('studio-equipment','Monitor Mounts','monitor-mounts',true,0),
('studio-lighting','Continuous Lighting','continuous-lighting',true,0),
('studio-lighting','Light Stands','light-stands',true,0),
('studio-lighting','Softbox','softbox',true,0),
('studio-lighting','Studio Lighting Kit','studio-lighting-kit',true,0),
('supports-and-stabilisation','Camera Supports','camera-supports',true,0),
('supports-and-stabilisation','Camera Tripods','camera-tripods',true,0),
('supports-and-stabilisation','Gimbals & Stabilisers','gimbals-and-stabilisers',true,0),
('supports-and-stabilisation','Monopods','monopods',true,0),
('supports-and-stabilisation','Tripod Heads','tripod-heads',true,0),
('supports-and-stabilisation','Video Tripods','video-tripods',true,0),
('tripods','Tripods','tripods',true,0),
('video-cameras','Body Cameras','body-cameras',true,0),
('video-cameras','Broadcast & Studio Cameras','broadcast-and-studio-cameras',true,0),
('video-cameras','Camcorders','camcorders',true,0),
('video-cameras','Cinema Cameras','cinema-cameras',true,0),
('video-cameras','Dash Cameras','dash-cameras',true,0),
('video-cameras','PTZ Cameras','ptz-cameras',true,0),
('video-cameras','Remote Cameras','remote-cameras',true,0),
('video-equipment','Monitor','monitor',true,0),
('video-equipment','Teleprompters','teleprompters',true,0),
('video-production-equipment','Camera & Video Monitors','camera-and-video-monitors',true,0),
('video-production-equipment','Camera Cages & Rigs','camera-cages-and-rigs',true,0),
('video-production-equipment','Camera Control Units','camera-control-units',true,0),
('video-production-equipment','Camera Rigs & Support','camera-rigs-and-support',true,0),
('video-production-equipment','Camera Setup Units','camera-setup-units',true,0),
('video-production-equipment','Camera Sliders','camera-sliders',true,0),
('video-production-equipment','Camera Sliders & Dollies','camera-sliders-and-dollies',true,0),
('video-production-equipment','Control Panels','control-panels',true,0),
('video-production-equipment','General Video Equipment','general-video-equipment',true,0),
('video-production-equipment','Module','module',true,0),
('video-production-equipment','Network & IP Video Equipment','network-and-ip-video-equipment',true,0),
('video-production-equipment','Production Switchers','production-switchers',true,0),
('video-production-equipment','Professional Media Drives','professional-media-drives',true,0),
('video-production-equipment','Professional Video','professional-video',true,0),
('video-production-equipment','PTZ Controllers','ptz-controllers',true,0),
('video-production-equipment','Remote Production Equipment','remote-production-equipment',true,0),
('video-production-equipment','Streaming Equipment','streaming-equipment',true,0),
('video-production-equipment','Teleprompters','teleprompters',true,0),
('video-production-equipment','Video Converters','video-converters',true,0),
('video-production-equipment','Video Recorders','video-recorders',true,0),
('video-production-equipment','Video Routing','video-routing',true,0),
('video-production-equipment','Video System','video-system',true,0),
('video-production-equipment','Video Transmission','video-transmission',true,0)) insert into public.catalogue_master_branches(category_id,name,slug,active,sort_order)
select c.id,d.name,d.slug,d.active,d.sort_order from data d join public.catalogue_master_categories c on c.slug=d.category_slug
on conflict (category_id,slug) do update set name=excluded.name,active=excluded.active,sort_order=excluded.sort_order;
