create table if not exists public.shipping_provider_catalog (
  provider_code text primary key,
  provider_name text not null,
  provider_type text not null check (provider_type in ('multi_carrier','direct_carrier')),
  connection_method text not null check (connection_method in ('api_credentials','oauth','account_credentials','manual')),
  website_url text, documentation_url text, setup_url text, description text, setup_instructions text,
  required_fields jsonb not null default '[]'::jsonb, capabilities jsonb not null default '{}'::jsonb,
  availability text not null default 'available' check (availability in ('available','setup_required','planned')),
  adapter_status text not null default 'planned' check (adapter_status in ('active','framework_ready','planned')),
  sort_order integer not null default 100, enabled boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

alter table public.shipping_provider_connections add column if not exists credentials_vault_id uuid;
alter table public.shipping_provider_connections drop constraint if exists shipping_provider_connections_provider_check;
alter table public.shipping_provider_connections add constraint shipping_provider_connections_provider_check
check (provider = any (array['parcel2go','sendcloud','shippo','shiptheory','scurri','metapack','linnworks','royalmail','evri','yodel','dpd','dhl','parcelforce','ups','fedex','dx','apc','inpost','whistl','amazon_shipping']));

alter table public.shipping_provider_catalog enable row level security;
drop policy if exists shipping_provider_catalog_public_select on public.shipping_provider_catalog;
create policy shipping_provider_catalog_public_select on public.shipping_provider_catalog for select to authenticated using (enabled=true);
grant select on public.shipping_provider_catalog to authenticated;

insert into public.shipping_provider_catalog
(provider_code,provider_name,provider_type,connection_method,website_url,documentation_url,setup_url,description,setup_instructions,required_fields,capabilities,availability,adapter_status,sort_order)
values
('parcel2go','Parcel2Go','multi_carrier','api_credentials','https://www.parcel2go.com','https://www.parcel2go.com/api/docs/','https://www.parcel2go.com/api/docs/','Multi-carrier shipping platform for quotes, orders, labels and tracking.','Create a Parcel2Go account, open the API area, create credentials, choose Sandbox or Live, then enter the Client ID and Client Secret in TradeFlow.','[{"key":"api_client_id","label":"API Client ID","type":"text","secret":false,"required":true},{"key":"api_client_secret","label":"API Client Secret","type":"password","secret":true,"required":true}]','{"quote":true,"order":true,"label":true,"tracking":true}','available','active',10),
('sendcloud','Sendcloud','multi_carrier','oauth','https://www.sendcloud.com','https://sendcloud.dev/','https://sendcloud.dev/','Multi-carrier shipping platform connecting your own carrier accounts.','Create and configure your Sendcloud business account. TradeFlow will use a secure authorisation flow when the Sendcloud adapter is enabled.','[]','{"quote":true,"order":true,"label":true,"tracking":true}','setup_required','planned',20),
('shippo','Shippo','multi_carrier','oauth','https://goshippo.com','https://docs.goshippo.com/','https://docs.goshippo.com/','Multi-carrier shipping platform with connected carrier accounts.','Create and configure your Shippo account. TradeFlow will use a secure authorisation flow when the Shippo adapter is enabled.','[]','{"quote":true,"order":true,"label":true,"tracking":true}','setup_required','planned',30),
('shiptheory','Shiptheory','multi_carrier','api_credentials','https://shiptheory.com','https://shiptheory.com/developer/','https://shiptheory.com/get-started/','Multi-carrier shipping platform with one API connection to supported carriers.','Create a Shiptheory account and obtain the API credentials from its developer area.','[{"key":"api_token","label":"API Token","type":"password","secret":true,"required":true}]','{"order":true,"label":true,"tracking":true}','setup_required','planned',40),
('scurri','Scurri','multi_carrier','api_credentials','https://www.scurri.com','https://docs.scurri.com/','https://www.scurri.com/','Multi-carrier shipping platform with a single API for supported carrier services.','Create a Scurri account and obtain the API credentials supplied for your account.','[{"key":"api_key","label":"API Key","type":"password","secret":true,"required":true},{"key":"api_secret","label":"API Secret","type":"password","secret":true,"required":false}]','{"order":true,"label":true,"tracking":true}','setup_required','planned',50),
('metapack','Metapack','multi_carrier','api_credentials','https://www.metapack.com','https://dev.metapack.com/','https://dev.metapack.com/','Multi-carrier delivery management platform with configured carriers and services.','Create/configure your Metapack account and obtain the credentials and account identifiers required for API access.','[{"key":"username","label":"Username","type":"text","secret":false,"required":true},{"key":"password","label":"Password","type":"password","secret":true,"required":true},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"order":true,"label":true,"tracking":true}','setup_required','planned',60),
('linnworks','Linnworks','multi_carrier','oauth','https://www.linnworks.com','https://docs.linnworks.com/','https://docs.linnworks.com/','Commerce and fulfilment platform with shipping integrations.','Create/configure your Linnworks account. TradeFlow will use a secure authorisation flow when the Linnworks adapter is enabled.','[]','{"order":true,"label":true,"tracking":true}','setup_required','planned',70),
('royalmail','Royal Mail','direct_carrier','api_credentials','https://www.royalmail.com','https://developer.royalmail.net/start','https://developer.royalmail.net/start','Direct Royal Mail API connection for supported shipping and tracking services.','Create a Royal Mail API account, register a TradeFlow application in My Apps, obtain the Client ID and Client Secret, and subscribe to the required API. Some APIs require Royal Mail approval.','[{"key":"client_id","label":"Client ID","type":"text","secret":false,"required":true},{"key":"client_secret","label":"Client Secret","type":"password","secret":true,"required":true}]','{"label":true,"tracking":true}','setup_required','planned',100),
('evri','Evri','direct_carrier','account_credentials','https://www.evri.com','https://www.evri.com/','https://www.evri.com/','Direct Evri business shipping connection.','Create/configure your Evri business account and obtain the API or account credentials required for your selected Evri service.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false},{"key":"api_secret","label":"API Secret","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',110),
('yodel','Yodel','direct_carrier','api_credentials','https://www.yodel.co.uk','https://developer.yodel.co.uk/','https://developer.yodel.co.uk/','Direct Yodel API connection.','Create a free Yodel API Developer Portal account, choose the API plan/application you need, then enter the credentials issued for that application.','[{"key":"client_id","label":"Client ID / API Key","type":"text","secret":false,"required":true},{"key":"client_secret","label":"Client Secret","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',120),
('dpd','DPD','direct_carrier','account_credentials','https://www.dpd.co.uk','https://www.dpd.co.uk/','https://www.dpd.co.uk/','Direct DPD business shipping connection.','Create/configure your DPD business account and obtain the API credentials supplied for your DPD integration.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"username","label":"Username","type":"text","secret":false,"required":false},{"key":"password","label":"Password","type":"password","secret":true,"required":false},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',130),
('dhl','DHL eCommerce UK','direct_carrier','api_credentials','https://www.dhl.com/gb-en','https://developer.dhl.com/api-reference/ecommerce-uk','https://developer.dhl.com/api-reference/ecommerce-uk','Direct DHL eCommerce UK API connection.','You need an active DHL eCommerce UK customer account. Follow the DHL onboarding process and obtain UAT or production Client ID and Client Secret.','[{"key":"client_id","label":"Client ID","type":"text","secret":false,"required":true},{"key":"client_secret","label":"Client Secret","type":"password","secret":true,"required":true},{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',140),
('parcelforce','Parcelforce','direct_carrier','account_credentials','https://www.parcelforce.com','https://www.parcelforce.com/','https://www.parcelforce.com/','Direct Parcelforce business shipping connection.','Create/configure your Parcelforce business account and obtain the API credentials required for your selected services.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',150),
('ups','UPS','direct_carrier','api_credentials','https://www.ups.com','https://developer.ups.com/get-started','https://developer.ups.com/get-started','Direct UPS API connection using OAuth 2.0.','Sign in with your UPS.com profile, create an application, link your shipper account, and obtain the Client ID and Client Secret.','[{"key":"client_id","label":"Client ID","type":"text","secret":false,"required":true},{"key":"client_secret","label":"Client Secret","type":"password","secret":true,"required":true},{"key":"account_number","label":"UPS Account Number","type":"text","secret":false,"required":false}]','{"label":true,"tracking":true,"quote":true}','setup_required','planned',160),
('fedex','FedEx','direct_carrier','api_credentials','https://www.fedex.com','https://developer.fedex.com/','https://developer.fedex.com/','Direct FedEx API connection using OAuth 2.0.','Create a project in the FedEx Developer Portal and obtain the API Key and Secret Key.','[{"key":"api_key","label":"API Key","type":"text","secret":false,"required":true},{"key":"secret_key","label":"Secret Key","type":"password","secret":true,"required":true},{"key":"account_number","label":"FedEx Account Number","type":"text","secret":false,"required":false}]','{"label":true,"tracking":true,"quote":true}','setup_required','planned',170),
('dx','DX','direct_carrier','account_credentials','https://www.dxdelivery.com','https://www.dxdelivery.com/','https://www.dxdelivery.com/','Direct DX business shipping connection.','Create/configure your DX business account and request the API credentials for the services you use.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"username","label":"Username","type":"text","secret":false,"required":false},{"key":"password","label":"Password","type":"password","secret":true,"required":false},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',180),
('apc','APC','direct_carrier','account_credentials','https://apc-overnight.com','https://apc-overnight.com/','https://apc-overnight.com/','Direct APC Overnight business shipping connection.','Create/configure your APC business account and obtain the API credentials supplied for your account.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',190),
('inpost','InPost','direct_carrier','account_credentials','https://inpost.co.uk','https://inpost.co.uk/','https://inpost.co.uk/','Direct InPost business shipping connection.','Create/configure your InPost business account and follow its developer/onboarding process for API access.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',200),
('whistl','Whistl','direct_carrier','account_credentials','https://www.whistl.co.uk','https://www.whistl.co.uk/','https://www.whistl.co.uk/','Direct Whistl business shipping connection.','Create/configure your Whistl business account and obtain the API credentials for the services you use.','[{"key":"account_number","label":"Account Number","type":"text","secret":false,"required":true},{"key":"api_key","label":"API Key","type":"password","secret":true,"required":false}]','{"label":true,"tracking":true}','setup_required','planned',210),
('amazon_shipping','Amazon Shipping','direct_carrier','oauth','https://shipping.amazon.co.uk','https://shipping.amazon.co.uk/','https://shipping.amazon.co.uk/','Amazon Shipping account connection.','Create/configure your Amazon Shipping account. TradeFlow will use a secure authorisation flow when the Amazon Shipping adapter is enabled.','[]','{"label":true,"tracking":true,"quote":true}','setup_required','planned',220)
on conflict (provider_code) do update set provider_name=excluded.provider_name,provider_type=excluded.provider_type,connection_method=excluded.connection_method,website_url=excluded.website_url,documentation_url=excluded.documentation_url,setup_url=excluded.setup_url,description=excluded.description,setup_instructions=excluded.setup_instructions,required_fields=excluded.required_fields,capabilities=excluded.capabilities,availability=excluded.availability,adapter_status=excluded.adapter_status,sort_order=excluded.sort_order,updated_at=now();

create or replace function public.subscriber_save_shipping_provider_connection(p_tenant_id uuid,p_provider text,p_environment text,p_credentials jsonb,p_config jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,vault as $function$
declare v_catalog public.shipping_provider_catalog%rowtype; v_secret_id uuid; v_connection_id uuid;
begin
 if auth.uid() is null or not private.has_tenant_permission(p_tenant_id,auth.uid(),'tenant.manage') then raise exception 'Not authorised'; end if;
 select * into v_catalog from public.shipping_provider_catalog where provider_code=p_provider and enabled=true;
 if not found then raise exception 'Shipping provider is not available'; end if;
 if p_environment not in ('sandbox','live') then raise exception 'Invalid environment'; end if;
 if coalesce(jsonb_typeof(p_credentials),'object')<>'object' or p_credentials='{}'::jsonb then raise exception 'Enter the required connection details'; end if;
 v_secret_id:=vault.create_secret(p_credentials::text,'tradeflow_shipping_credentials_'||p_tenant_id::text||'_'||p_provider,'TradeFlow shipping provider credentials');
 insert into public.shipping_provider_connections(tenant_id,provider,status,connection_type,environment,auth_mode,credentials_vault_id,metadata,updated_at)
 values(p_tenant_id,p_provider,'pending','subscriber_account',p_environment,v_catalog.connection_method,v_secret_id,coalesce(p_config,'{}'::jsonb),now())
 on conflict (tenant_id,provider) do update set status='pending',environment=excluded.environment,auth_mode=excluded.auth_mode,credentials_vault_id=excluded.credentials_vault_id,metadata=excluded.metadata,disconnected_at=null,updated_at=now()
 returning id into v_connection_id;
 return jsonb_build_object('ok',true,'connection_id',v_connection_id,'status','pending','adapter_status',v_catalog.adapter_status);
end;$function$;

create or replace function public.shipping_provider_credentials_for_service(p_connection_id uuid)
returns jsonb language plpgsql security definer set search_path=public,private,vault as $function$
declare v_secret text;
begin
 if current_user<>'service_role' then raise exception 'Not authorised'; end if;
 select ds.decrypted_secret into v_secret from vault.decrypted_secrets ds join public.shipping_provider_connections c on c.credentials_vault_id=ds.id where c.id=p_connection_id;
 if v_secret is null then raise exception 'Provider credentials not found'; end if;
 return v_secret::jsonb;
end;$function$;

revoke execute on function public.subscriber_save_shipping_provider_connection(uuid,text,text,jsonb,jsonb) from anon;
grant execute on function public.subscriber_save_shipping_provider_connection(uuid,text,text,jsonb,jsonb) to authenticated;
revoke execute on function public.shipping_provider_credentials_for_service(uuid) from public,anon,authenticated;
grant execute on function public.shipping_provider_credentials_for_service(uuid) to service_role;
